### PR TITLE
upgrade for v0.10.10

### LINKED ISSUE #125: Update to v.10.10
Pixelfed v.10.10 is out 🙂 https://github.com/pixelfed/pixelfed/releases/tag/v0.10.10

How should we manage the Post Deployment step ? Any idea @yalh76 ?

### PR DESCRIPTION
**Pull request by yalh76**
## Problem
- *Fix #125*

## Solution
- *upgrade for v0.10.10*

### CODE REVIEW

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
# Own CI result for Revision: 982814e82a5ea3256c99a334768f976bfb600360 
image

**Comment by lapineige** [comment]
Thanks a lot for the hard work @yalh76 :smiley:

**Comment by lapineige** [comment]
Upgrade fails on my side, because of the use of about 2GB of RAM, which overload my 3GB of RAM, and then it swaps, takes hours, and fails because of a timeout somewhere.
Restoration fails too, probably because of the same issue.

That amount of RAM use if very strange…

**Pull request merged**
