### PR TITLE
Fix #111

### LINKED ISSUE #111: Unit pixelfed-horizon.service not found.
Using latest master, I found out that the pixelfed-horizon service doesn't exist.
`Failed to start pixelfed-horizon.service: Unit pixelfed-horizon.service not found.`

### PR DESCRIPTION
**Pull request by yalh76**
## Problem
- *Fix #111*

## Solution
- *Replace ${app}-horizon by supervisor*

## PR Status
- [x] Code finished.
- [x] Tested with Package_check.
- [x] Fix or enhancement tested.
- [x] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Package_check results
---
[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/pixelfed_ynh%20PR112%20(yalh76)/)

### CODE REVIEW

**Comment by lapineige** [comment]
Looks good to me, even if I don't understand fully all the details. I'll try it.

**Comment by lapineige** [comment]
Upgrade failed after that: 
> Info: Updating php dependencies...
Warning: ynh_composer__2: line 9: 18831 Killed                  COMPOSER_HOME="$workdir/.composer" php${phpversion} "$workdir/composer.phar" $commands -d "$workdir" --quiet --no-interaction
Warning: [Error] Upgrade failed.

And it created a very high load on the server (up to 35).

**Comment by yalh76** [comment]
> 
> 
> Upgrade failed after that:
> 
> > Info: Updating php dependencies...
> > Warning: ynh_composer__2: line 9: 18831 Killed                  COMPOSER_HOME="$workdir/.composer" php${phpversion} "$workdir/composer.phar" $commands -d "$workdir" --quiet --no-interaction
> > Warning: [Error] Upgrade failed.
> 
> And it created a very high load on the server (up to 35).
> 
> edit: in the end of the restore
> 
> > Error: Could not upgrade pixelfed: This action broke dpkg/APT (the system package managers)… You can try to solve this issue by connectingthrough SSH and running `sudo apt install --fix-broken` and/or `sudo dpkg --configure -a`.
> > Error: Packagers /!\ This app manually modified some system configuration files! This should not happen! If you need to do so, you should implement a proper conf_regen hook. Those configuration were affected:
> > - /etc/default/glances

seems strange as package_check is ok on https://ci-apps-dev.yunohost.org/jenkins/job/pixelfed_ynh%20PR112%20(yalh76)/ and on my own CI for stretch and for buster

I've already seen that composer fails because it makes too much requests at github...

I will apply last example_ynh and see what's package_check result

**Comment by yalh76** [comment]
@lapineige last package_check is ok on ci-apps-dev and on my own CI for stretch and buster.
Can I merge into testing ?

**Comment by lapineige** [comment]
I don't know, I can't test right now on my side.

As it's only for testing, which has no other PR, I would say yes.

**Pull request merged**
