### PR TITLE
Fix php conf & image permissions

### PR DESCRIPTION
**Pull request by lapineige**
#223 

PHP config was not done correctly, using extra_php.conf group wasn't overwriten correctly.

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
!testme

**Review by yalh76 — COMMENTED** [review]
shouldn't it be `php-fpm.conf` instead of `php_fpm.conf` ?

**Comment by lapineige** [comment]
Oh yes, thank you !

**Comment by lapineige** [comment]
!testme

**Comment by Jaxom99** [comment]
Thanks for looking into it so quickly ! So if I read the test right, apart from the php_fpm settings that causes a linter error, all is good ? I can test on my setup anytime (just remind me how to switch branches to install this one ?)

**Comment by lapineige** [comment]
In my case, for an unknown reason this breaks image preview on upload. Don't test it now, it won't work :)

**Comment by lapineige** [comment]
> (just remind me how to switch branches to install this one ?)

`yunohost app upgrade pixelfed -u https://github.com/YunoHost-Apps/pixelfed_ynh/tree/fix_php_conf_image-permissions`

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
I reverted to normal extra_php.conf, as the new option implemented by @alexAubin makes it way easier and cleaner to set the group for php workers.
This should solve the issue for good.

**Comment by lapineige** [comment]
Thanks @alexAubin

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
Here we go !

**Comment by lapineige** [comment]
Everything is back to normal, at last :)

**Pull request merged**
