### PR TITLE
Upgrade to 0.10.8

### PR DESCRIPTION
**Pull request by yalh76**
## Solution
- *Upgrade to 0.10.8*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Package_check results
---
[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/pixelfed_ynh%20PR96%20(yalh76)/)

### CODE REVIEW

**Comment by lapineige** [comment]
I was going to do it, I'm glad to see it's already done :D
I'm trying it right now :)

**Comment by yalh76** [comment]
oupsi, next time I will let you more time to do it ^^

Let me know if it's ok. I'm only doing package_check tests as I don't use it ^^

**Comment by lapineige** [comment]
Well, nothing to report, it went well :)

**Comment by lapineige** [comment]
Done, nothing to report :)
Let's merge ?

**Pull request merged**
