### PR TITLE
Fix images not loading and feed not updating on a fresh install

### PR DESCRIPTION
**Pull request by NorbiPeti**
## Problem

- After installing the app images I uploaded did not load (preview was blurred, placeholder instead of the image)
- After using the app for a while I noticed my feed doesn't get updated (last post 10+ days ago - I don't check it often atm)

## Solution

- I've changed the install/update scripts to run the artisan commands as the pixelfed user instead of root so that the cached files are created with the correct user+group
- Moved the permission fix step before the deployment step on fresh installs (this way the configs get cached after the fix)

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

Tested on a VirtualBox install of YunoHost with fresh install & in-place upgrade

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by lapineige** [comment]
Thanks !

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
Is there any other person who tried this branch ? Does it looks good ? :)

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
> Is there any other person who tried this branch ? Does it looks good ? :)

:up:

**Comment by lapineige** [comment]
How does this interacts with #259 ? :thinking:

**Comment by NorbiPeti** [comment]
Well, in theory they are unrelated, though conflicts in the scripts are possible.

**Comment by OniriCorpe** [comment]
!testme

**Comment by lapineige** [comment]
What's the status of this ?
Any relation with #271 ?

**Comment by OniriCorpe** [comment]
Just tested on a fresh install with the postgresql fix but this one and media can be uploaded but pixelfed is unable to show them
So the 2 fixes are needed

**Comment by lapineige** [comment]
Feel free to merge then if manual testing of this one give nice results :)

**Pull request merged**
