### PR TITLE
Better log file permissions + fix redis config + laravel log rotate

### LINKED ISSUE #199: Implement logrotate on laravel log
Laravel log file is huge after a while, because it's never cleaned up. It's already 22kB after first running Pixelfed.

We should implement logrotate to save storage space.

File to logrotate : `/var/www/pixelfed/storage/logs/laravel.log`

### LINKED ISSUE #202: Oops. Something went wrong after update
Hello,

I did an update from 0.11.4-ynh4 to 0.11.4-ynh5 on February 19th and did not notice any error while updating.
When posting a status now I always get a message "Oops. Something went wrong". I ignored this message because everything seemed to be ok. The status is visible in the timeline.
Now I found out that there are problems: In the database tables "hashtag" and "status_hashtags" no new entries are written. And in the table "statuses" the field "entities" stays empty.

Is there a way to find what's the problem on my instance running on a local RaspberryPi?

Best regards

### PR DESCRIPTION
**Pull request by lapineige**
Log file permission fixes + Fix #202 + Fix #199

### CODE REVIEW

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
> 181433 INFO DEBUG - + touch /var/log/pixelfed/pixelfed-horizon.log
181433 INFO DEBUG - + chown -R pixelfed: /var/log/pixelfed/
181433 INFO DEBUG - + chmod -R 600 pixelfed: /var/log/pixelfed/
181433 INFO WARNING - chmod: cannot access 'pixelfed:': No such file or directory

I don't get it.

**Comment by yalh76** [comment]
!testme

**Comment by lapineige** [comment]
@yalh76 I canceled the first CI test as the install was broken with the quoted error. Hence it was pointless to let it continue.

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
Manual testing went fine.

**Comment by lapineige** [comment]
Why does CI fails with this ?
```
222492 INFO [#########+..........] > Creating log file... [.2 minutes]
222535 WARNING chmod: cannot access 'pixelfed:': No such file or directory
```
At https://github.com/YunoHost-Apps/pixelfed_ynh/blob/testing/scripts/install#L137

The folder was just created !?

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
It was a syntax issue.

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
Will not wait for #203, this PR brings lighter changes so I prefer not to be too hasty.

**Comment by lapineige** [comment]
For later use : 

> Peak RAM usage during this test: 1167MB
RAM usage diff after test: 945MB

And in #203 :
> Peak RAM usage during this test: 1162MB
RAM usage diff after test: 500MB

**Pull request merged**
