### PR TITLE
Fix

### PR DESCRIPTION
**Pull request by ericgaspar**
- Remove `extra_php_dependencies`

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by yalh76** [comment]
??? https://github.com/YunoHost-Apps/pixelfed_ynh/pull/168

**Comment by lapineige** [comment]
Oh yeah, I also forgot that :sweat_smile:

I cancelled the CI.

**Comment by lapineige** [comment]
So we close this ?

**Pull request closed without merging**
