### PR TITLE
Fix mail smtp

### PR DESCRIPTION
**Pull request by themancalledjakob**
## Problem

- *To fix email sending* #228 

## Solution

- *adjust manifest and .env to match with https://yunohost.org/fr/packaging_apps_resources#system-user*

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Comment
I am unsure whether port `25` or `587` should used in [`.env`](https://github.com/themancalledjakob/pixelfed_ynh/blob/fix-mail-smtp/conf/.env#L89)

### CODE REVIEW

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
Thank a lot for that PR !! :smiley:

**Comment by themancalledjakob** [comment]
damn, somehow i cannot figure out any working smtp settings. it looks as if the mailserver always attempts a TLS connection, nevermind the MAIL_ENCRYPTION=null setting in `.env`, and I cannot figure out how to set up TLS properly.

the `sendmail` solution does work though. is there any reason why smtp should be preferred?

**Comment by lapineige** [comment]
I don't know. We should ask Yunohost devs

**Comment by lapineige** [comment]
!bookwormtestme

**Comment by themancalledjakob** [comment]
> I don't know. We should ask Yunohost devs

I have a hunch, that we should just use sendmail.
If you run `$ man sendmail`, it will tell you that it's not ancient sendmail, but actually postfix.
It's sending emails with these settings `/etc/postfix/main.cf`.
Looking in these settings, it appears that they are neatly tied to yunohost setup, even including ldap user accounts and TLS.

and also: it just works :)

**Comment by lapineige** [comment]
Then that's perfect, let's go for it ? :)

**Comment by themancalledjakob** [comment]
yep, i prepared a [branch with sendmail](https://github.com/themancalledjakob/pixelfed_ynh/tree/fix-mail-sendmail) and will quickly do a fresh install on my yunohost to verify that it indeed works out of the box

**Comment by themancalledjakob** [comment]
alright, here it is: #230

**Comment by lapineige** [comment]
It's a bit confusing, but cool, having another PR (instead of changing it here) is cool too.
Archiving this then.

**Comment by themancalledjakob** [comment]
aha, learned something.
Next time, I'll rather edit commits of an existing PR :)

**Comment by lapineige** [comment]
Well it reduces the commit history when it's another PR, but it also split the discussion in 2 places, so in that case (a minor change) I would rather keep it here :)

**Pull request closed without merging**
