### PR TITLE
Upgrade to v0.12.4 (#277)

### LINKED ISSUE #275: implement notify server
https://github.com/pixelfed/notify

### PR DESCRIPTION
**Pull request by lapineige**
* Upgrade sources
- `main` v0.12.4: https://github.com/pixelfed/pixelfed/releases/tag/0.12.4

* Auto-update READMEs

* Here goes PHP 8.3

Fix #275 ?

### CODE REVIEW

**Comment by lapineige** [comment]
Testers needed, CI was already used for the previous PR.

**Comment by jothgard** [comment]
Upgrade did work just fine, but seems not to refresh to enable Notifications, Says that PHP is still on 8.2.25
output:
**/var/www/pixelfed# php artisan app:push-gateway-refresh
Composer detected issues in your platform:

Your Composer dependencies require a PHP version ">= 8.3.0". You are running 8.2.25.

PHP Fatal error:  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.3.0". You are running 8.2.25. in /var/www/pixelfed/vendor/composer/platform_check.php on line 26
**

**Comment by jothgard** [comment]
> Testers needed, CI was already used for the previous PR.

And my config /var/www/pixelfed/vendor/composer/platform_check.php says : 

<?php

// platform_check.php @generated by Composer

$issues = array();

if (!(PHP_VERSION_ID >= 80300)) {

Should be on 8.3.0 right??

**Comment by jothgard** [comment]
> > Testers needed, CI was already used for the previous PR.
> 
> And my config /var/www/pixelfed/vendor/composer/platform_check.php says :
> = 80300)) { Should be on 8.3.0 right??

oh, did try to remove one 0. seems to work now :D!

**Comment by lapineige** [comment]
Uh, what's that trick :thinking:

**Comment by jothgard** [comment]
> Uh, what's that trick 🤔

Yes! For me! Thanks for your help !! Try it and see if it is also fix for you.

**Comment by jothgard** [comment]
Only issue is i cang get notification work or instagram import, just gets stuck in uploading, Should work on this latest version?

**Pull request merged**
