### PR TITLE
fix_services

### LINKED ISSUE #111: Unit pixelfed-horizon.service not found.
Using latest master, I found out that the pixelfed-horizon service doesn't exist.
`Failed to start pixelfed-horizon.service: Unit pixelfed-horizon.service not found.`

### PR DESCRIPTION
**Pull request by yalh76**
## Problem
- *Fix #111*

## Solution
- *Replace ${app}-horizon by supervisor*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Package_check results
---
[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/pixelfed_ynh%20PR116%20(yalh76)/)

### CODE REVIEW

**Comment by lapineige** [comment]
Upgrade of php dependencies seems to take too long:

> Info: [######+.............] > Updating php dependencies...
   Warning: ynh_composer__2: line 9: 18923 Killed                  COMPOSER_HOME="$workdir/.composer" php${phpversion} "$workdir/composer.phar" $commands -d "$workdir" --quiet --no-interaction
Warning: [Error] Upgrade failed.

I wonder if I don't have a general issue in my system :thinking:

**Comment by yalh76** [comment]
During my tests, several times, I've seen errors during the composer part.
Mainly because composer download a lot of stuff at github... And if you retry it will work...

So let's try when you have time. And if it fails, launch the upgrade from the command line with `--debug`, you will see what's happen during composer

**Comment by lapineige** [comment]
What is strange is that it's the first time I experience that this php composer upgrade takes forever, and that the process is killed in the end. And I tried 5 times.

I'll try again with --debug.

**Comment by lapineige** [comment]
Still fails, same issue… :(

The process takes too long, and is killed.

> 222820 DEBUG ++ ynh_handle_getopts_args --phpversion=7.3 --workdir=/var/www/pixelfed --commands=update                                     222820 DEBUG ++ set +o xtrace                                                                                                              
222820 DEBUG ++ workdir=/var/www/pixelfed                                                                                                  
222820 DEBUG ++ phpversion=7.3                                                                                                             
222820 DEBUG ++ COMPOSER_HOME=/var/www/pixelfed/.composer                                                                                  
222820 DEBUG ++ php7.3 /var/www/pixelfed/composer.phar update -d /var/www/pixelfed --no-interaction                                        
227328 DEBUG Do not run Composer as root/super user! See https://getcomposer.org/root for details                                          
228229 DEBUG Loading composer repositories with package information                                                                        
229932 DEBUG Updating dependencies (including require-dev)                                                                                 
    2850622 DEBUG ynh_composer__2: line 9: 27201 Killed                  COMPOSER_HOME="$workdir/.composer" php${phpversion} "$workdir/comp
oser.phar" $commands -d "$workdir" --no-interaction                                                                                        
2850929 DEBUG + ynh_exit_properly

**Comment by yalh76** [comment]
an you check how is the memory of you YunoHost whit the command: `free`

**Comment by lapineige** [comment]
I can't really, as the load goes up to >35 and the connection is almost closed… it's not responding enough to get the memory info.
But I didn't see anything strange afterwards… I'll check again :thinking:

**Comment by yalh76** [comment]
@lapineige do we merge ?

**Comment by lapineige** [comment]
I'll trust you on this one. I'm merging

**Pull request merged**
