### PR TITLE
Apply last example_ynh

### PR DESCRIPTION
**Pull request by yalh76**
## Problem
- *Description of why you made this PR*

## Solution
- *Apply last example_ynh*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

### CODE REVIEW

**Review by lapineige — APPROVED** [review]
Looks good to me overall, but I didn't go into the details. Install/upgrade not tested

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
#Own CI results for Revision: 10a2af76c2e550b060b229aee739020888529451
image

**Pull request merged**
