### PR TITLE
Update to 0.10.9

### PR DESCRIPTION
**Pull request by lapineige**
https://github.com/pixelfed/pixelfed/releases/tag/v0.10.9

## PR Status
- [x] Code finished.
- [x] Tested with Package_check.
- [x] Fix or enhancement tested.
- [x] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Package_check results
---
*If you have access to [App Continuous Integration for packagers](https://yunohost.org/#/packaging_apps_ci) you can provide a link to the package_check results like below, replacing '-NUM-' in this link by the PR number and USERNAME by your username on the ci-apps-dev. Or you provide a screenshot or a pastebin of the results*

[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/pixelfed_ynh%20PR-NUM-%20(USERNAME)/)

### CODE REVIEW

**Comment by lapineige** [comment]
Upgrade from 0.10.8 went well :)

**Comment by lapineige** [comment]
I can't promise to regularly spend some time working on it, and my skills are quite limited (don't ask me to deal with php stuff :joy:), but for such kind of minor update, why not :)

**Comment by yalh76** [comment]
Not a problem, but as you use this package, you will be more aware of the changes than I'm.
I added you in @YunoHost-Apps/pixelfed group, you should be able to what you need on https://github.com/YunoHost-Apps/pixelfed_ynh.

And created draft PR https://github.com/YunoHost-Apps/pixelfed_ynh/pull/105. I let you make the changes you want and merge it into testing ;) 

```
   {
        "name": "John doe",
        "email": "john.doe@example.com",
        "url": "http://example.com"
    },
```

**Comment by lapineige** [comment]
Ok, thank you :)

In any case if I submit a PR in testing, I'll ask you for review before merging to master.

**Pull request merged**
