### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by lapineige**
- #176 upgrade to 0.11.3
- #173 better `.env` permissions (allows admin UI to edit it)
- redis fix

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by lapineige** [comment]
!gogogadgetoci

**Comment by yalh76** [comment]
!testme

**Review by yalh76 — APPROVED** [review]

**Comment by yalh76** [comment]
> What does that updater is supposed to do ?

Do a PR when there is a new version of the upstream

**Comment by yalh76** [comment]
Do we merge ?

**Review by alexAubin — APPROVED** [review]
LGTM

**Pull request merged**
