### PR TITLE
fix ynh_install_php

### PR DESCRIPTION
**Pull request by yalh76**
to solve issue https://github.com/YunoHost-Apps/phpmyadmin_ynh/pull/86#issuecomment-484251574

Revision: 1c2b08f14d75fc43ece067106ec7cd1e2e9b56d7 
Capture

### CODE REVIEW

**Comment by lapineige** [comment]
I can't upgrade to this version (from testing).

`Unable to update core dependencies with Composer.` again.

I suppose I need to do a fresh install ?

**Comment by lapineige** [comment]
I can confirm that removing Pixelfed solves the issue (at least the removing part is correct).
I'll try a new install.

**Comment by yalh76** [comment]
> 
> 
> I can't upgrade to this version (from testing).
> 
> `Unable to update core dependencies with Composer.` again.
> 
> I suppose I need to do a fresh install ?

Do you have the logs of the failed upgrade to see what's happens ?

**Comment by lapineige** [comment]
After installing phpmyadmin then pixelfed (from this branch), both seems to work well together.

I guess it's fixed ?

**Comment by lapineige** [comment]
Ok I uninstalled phpmyadmin and pixelfed. Then I tried to install pixelfed, and I still have the same error message.

I also tested this in addition to #36 and #27, merged into master, same issue.

**Comment by yalh76** [comment]
I've updated the composer. Installation might work now

**Comment by lapineige** [comment]
I confirm it works :slightly_smiling_face:

**Pull request merged**
