### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by yalh76**
## Problem
- *#106*
- *#107*

## Solution
- *Update dependencies*
- *Split each helper in its own file*
- *Switch horizon service to supervisor*
- *Add cron*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Package_check results
---
[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/pixelfed_ynh%20PR110%20(yalh76)/)

### CODE REVIEW

**Comment by lapineige** [comment]
Upgrade went fine (from master) :)

**Comment by lapineige** [comment]
No it didn't : now my Pixelfed is crashed (by the cron ?). After cleaning artisan cache, I no longer have a blank page, but Pixelfed UI with a "something went wrong" message.
Also I missed an error with horizon service not being recognized or something like that.

I'm removing it and restoring the backup.

**Comment by yalh76** [comment]
Well, I will install one pixelfed_ynh to see if also have issues....

**Comment by lapineige** [comment]
I'm sorry but I have to testing server to do so, it's only my production server and I need it right now ^^

**Comment by yalh76** [comment]
> 
> 
> I'm sorry but I have to testing server to do so, it's only my production server and I need it right now ^^

No problem, I just installed a pixelfed instance and will make some tests..

**Comment by yalh76** [comment]
Well.. after two days, the test instance is still up... I will try to install master version and upgrade to testing to see if there is an issue...

**Comment by yalh76** [comment]
Made an installation from master and upgraded to testing. Launched several artisan commands and the instance is still OK.
So if someone has time to test and upgrade ^^

**Comment by lapineige** [comment]
I'll try again :)

**Comment by lapineige** [comment]
Again, my instance went to the "Something went wrong" state :sweat_smile:

`/var/log/pixelfed/pixelfed-horizon.log` is kind of empty:

>Horizon started successfully.
[2020-05-01 08:44:36][1] Processing: App\Jobs\InboxPipeline\InboxWorker
[2020-05-01 08:44:36][1] Processed:  App\Jobs\InboxPipeline\InboxWorker
[2020-05-01 09:06:39][1] Processing: App\Jobs\InboxPipeline\InboxWorker
[2020-05-01 09:06:40][1] Failed:     App\Jobs\InboxPipeline\InboxWorker
[2020-05-01 09:06:40][2] Processing: App\Jobs\InboxPipeline\InboxWorker
[2020-05-01 09:06:40][2] Processed:  App\Jobs\InboxPipeline\InboxWorker
[2020-05-01 09:06:40][3] Processing: App\Jobs\LikePipeline\LikePipeline
[2020-05-01 09:06:40][3] Processed:  App\Jobs\LikePipeline\LikePipeline
[2020-05-01 09:35:48][4] Processing: App\Jobs\InboxPipeline\InboxWorker
[2020-05-01 09:35:49][4] Processed:  App\Jobs\InboxPipeline\InboxWorker

Looking at `./storage/logs/laravel.log`, I see these errors:
> tail -n 500 ./storage/logs/laravel.log | grep ERROR
[2020-05-01 16:05:51] production.ERROR: could not find driver (SQL: select * from "profiles" where "domain" is null and "username" = MyPseudo and "profiles"."deleted_at" is null limit 1) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 0): could not find driver (SQL: select * from \"profiles\" where \"domain\" is null and \"username\" = MyPseudo and \"profiles\".\"deleted_at\" is null limit 1) at /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669)

> [2020-05-01 16:05:55] production.ERROR: could not find driver (SQL: select * from "profiles" where "domain" is null and "username" = MyPseudo and "profiles"."deleted_at" is null limit 1) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 0): could not find driver (SQL: select * from \"profiles\" where \"domain\" is null and \"username\" = MyPseudo and \"profiles\".\"deleted_at\" is null limit 1) at /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669)


>[2020-05-01 16:06:06] production.ERROR: The provided cwd "" does not exist. {"exception":"[object] (Symfony\\Component\\Process\\Exception\\RuntimeException(code: 0): The provided cwd \"\" does not exist. at /var/www/pixelfed/vendor/symfony/process/Process.php:336)

The same 3 errors each ~1m.

I also saw this one:
> production.ERROR: Key path "file:///var/www/pixelfed/storage/oauth-public.key" does not exist or is not readable {"exception":"[object] (LogicException(code: 0): Key path \"file:///var/www/pixelfed/storage/oauth-public.key\" does not exist or is not readable at /var/www/pixelfed/vendor/league/oauth2-server/src/CryptKey.php:48)

**Comment by yalh76** [comment]
Can you provide your upgrade logs ?

**Comment by lapineige** [comment]
https://vps.lapineige.fr/privatebin/?5358b2547b023ada#ANzoBaDkDBgb1HQpfC2vHovAu1N61jpFrLucmbBTD4g=

**Comment by yalh76** [comment]
I've updated the php7.3 dependencies. That should solve `production.ERROR: could not find driver`
I've also done a package_check and it's all ok.
If someone can test an upgrade and let know if it has gone fine or not.

**Comment by lapineige** [comment]
Upgraded again yesterday, it didn't crash yet :)

**Comment by yalh76** [comment]
well let me know if it's still ok we will merge ;)

**Comment by lapineige** [comment]
It's still up and running. Let's merge.

**Pull request merged**
