### PR TITLE
Testing : Switch back to php-redis for Nextcloud compatibility + php-imagick fix

### PR DESCRIPTION
**Pull request by lapineige**
## Problem

- #165 
- Php7.4-imagick is also creating conflicts

## Solution

- Switch to php-redis
- #183 

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
This will need user testing, to be sure it won't break anything in the app…

**Comment by lapineige** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Pull request merged**
