### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by yalh76**
## Solution
- [x] *Update readme*
- [x] *V0.9.0*
- [x] *fix ynh_install_php*
- [x] *Adding few automations*
- [x] *Apply last example_ynh*

## PR Status
- [x] Code finished.
- [x] Tested with Package_check.
- [x] Fix or enhancement tested.
- [x] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
- [ ] **Code review**
- [ ] **Approval (LGTM)**  
*Code review and approval have to be from a member of @YunoHost/apps group*
- **CI succeeded** : 
[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/pixelfed_ynh_PR39%20(yalh76)/)  
Revision: fc7de64be671ed3b14ab86a03399c4f3eb42a3d3
fc7de64be671ed3b14ab86a03399c4f3eb42a3d3

When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by Jibec** [comment]
Congratulations! Sorry for my lack of time, the few I have is invested in Fedora localization and weblate for now.

**Comment by yalh76** [comment]
> 
> Congratulations! Sorry for my lack of time, the few I have is invested in Fedora localization and weblate for now.

No pbs, it(s why I moved forward ^^

Can you give me access to https://github.com/YunoHost-Apps/funkwhale_ynh also ? I don't want to be too pushy ;)

**Comment by Jibec** [comment]
Le 22/05/2019 à 18:08, yalh76 a écrit :
> Can you give me access to 
> https://github.com/YunoHost-Apps/funkwhale_ynh also ? I don't want to 
> be too pushy ;) 

nope sorry, Funkwhale is a tool I use, I still maintain it (but slowly)

**Comment by yalh76** [comment]
> 
> Le 22/05/2019 à 18:08, yalh76 a écrit :
> Can you give me access to https://github.com/YunoHost-Apps/funkwhale_ynh also ? I don't want to be too pushy ;)
> nope sorry, Funkwhale is a tool I use, I still maintain it (but slowly)

no pb, is I can do something to help you don't hesitate to ask ;) as bad as my developing skills are ;p

**Comment by kay0u** [comment]
Hi,

Maybe you could work on Funkwhale together? Several maintainers are not prohibited:-)

**Pull request merged**
