### PR TITLE
Testing : v12.1 + swap to admin doc + readme i18n

### PR DESCRIPTION
**Pull request by ericgaspar**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by lapineige** [comment]
This will require manual testing. I'll see if I have time to upgrade.
Testers welcome :)

**Comment by justdaj** [comment]
what do I need to do to help?

**Comment by lapineige** [comment]
`yunohost app upgrade pixelfed -u https://github.com/YunoHost-Apps/pixelfed_ynh/tree/testing` to try upgrading to it :)

**Comment by justdaj** [comment]
The upgrade appears to be fully operational for me.  I went from 0.11.13 -> 0.12.1.

Output of the upgrade script below for info

```
Info: Now upgrading pixelfed…
Info: Creating a safety backup prior to the upgrade
Info: Collecting files to be backed up for pixelfed…
Info: Declaring files to be backed up...
Info: Backing up the PostgreSQL database...
Info: Backup script completed for pixelfed. (YunoHost will then actually copy those files to the archive).
Info: Creating a backup archive from the collected files…
Info: The archive will contain about 7.8GB of data.
   Success! Backup created: pixelfed-pre-upgrade2
Success! Backup deleted: pixelfed-pre-upgrade1
Info: Updating sources...
Info: Updating system_user...
Info: Updating install_dir...
Info: Updating permissions...
Info: Updating apt...
Info: Updating database...
Info: [....................] > Stopping a supervisor service...
Info: The service pixelfed-horizon has correctly executed the action stop.
Info: [+...................] > Ensuring downward compatibility...
Info: [#+..................] > Upgrading source files...
Info: [##..................] > Patching source files...
Info: [##+.................] > Upgrading PHP-FPM configuration...
Info: [###+................] > Upgrading NGINX web server configuration...
Info: [####+...............] > Updating composer...
Info: [#####...............] > Patching permissions (for version 0.11.5 and newer)...
Info: [#####+..............] > Deploying...
Warning: fatal: not a git repository (or any of the parent directories): .git
Info: [######+.............] > Creating log file...
Info: [#######+............] > Upgrading cron file...
Info: [########............] > Upgrading supervisor configuration...
Info: [########+...........] > Upgrading logrotate configuration...
Info: [#########+..........] > Integrating service in YunoHost...
Info: [##########+.........] > Starting a supervisor service...
Info: The service pixelfed-horizon has correctly executed the action start.
Info: [####################] > Upgrade of pixelfed completed
Success! pixelfed upgraded
Success! Upgrade complete
```

**Comment by Salamandar** [comment]
Well I guess we can merge this then, if @justdaj confirms their installation is working :)

**Comment by justdaj** [comment]
I can confirm no issues since upgrading two weeks ago, for me.  (254 users).

**Comment by webmink** [comment]
I have had an identical experience to @justdaj  so suspect this is ready to go (especially as there's now a bump to 12.3 available...)

**Comment by Salamandar** [comment]
Ok let's go.

**Pull request merged**
