### PR TITLE
Upgrade to v0.10.6

### PR DESCRIPTION
**Pull request by ahstro**
## Problem
- App is not up-to-date

## Solution
- Upgrade to latest version (0.10.6)

## PR Status
- [x] Code finished.
- [ ] Tested with Package_check.
- [x] Fix or enhancement tested.
- [x] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Package_check results
---
[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/pixelfed_ynh%20PR84%20(yalh76)/)

### CODE REVIEW

**Comment by lapineige** [comment]
Upgrade fails, with an error like that: 
> Warning: [DEBUG]: DEBUG   - DETAIL:  Key (uri)=([https://MastodonStatusURL]) is duplicated. (SQL: alter table "statuses" add constraint "statuses_uri_unique" unique ("uri"))
Warning: [DEBUG]: DEBUG   -
Warning: [DEBUG]: DEBUG   -   at /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664
Warning: [DEBUG]: DEBUG   -     660|         // If an exception occurs when attempting to run a query, we'll format the error
Warning: [DEBUG]: DEBUG   -     661|         // message to include the bindings with SQL, which will make this exception a
Warning: [DEBUG]: DEBUG   -     662|         // lot more helpful to the developer instead of just the database's errors.
Warning: [DEBUG]: DEBUG   -     663|         catch (Exception $e) {
Warning: [DEBUG]: DEBUG   -   > 664|             throw new QueryException(
Warning: [DEBUG]: DEBUG   -     665|                 $query, $this->prepareBindings($bindings), $e
Warning: [DEBUG]: DEBUG   -     666|             );
Warning: [DEBUG]: DEBUG   -     667|         }
Warning: [DEBUG]: DEBUG   -     668|
Warning: [DEBUG]: DEBUG

That status doesn't even exist anymore.
I had the same issue with a status of mine, I deleted it, it worked. For this one (not from me), which is also a comment, deleting it from Mastodon doesn't solve the issue :(

**Comment by lapineige** [comment]
This is a known issue: https://github.com/pixelfed/pixelfed/issues/1701

I'd suggest to wait until it's solved before merging.

**Comment by ahstro** [comment]
Strange, I tried upgrading and it worked. Oh well, guess waiting for that issue to be closed is the smartest move here.

**Comment by capmisson** [comment]
@ahstro what did you upgraded to make it work?

**Comment by ahstro** [comment]
@capmisson I installed Pixelfed from the upstream `testing` branch, then upgraded from my fork

**Comment by lapineige** [comment]
https://github.com/pixelfed/pixelfed/releases/tag/v0.10.4 is out, let's update this PR ? :)

**Comment by lapineige** [comment]
https://github.com/pixelfed/pixelfed/releases/tag/v0.10.5, in fact.

**Comment by dansup** [comment]
v0.10.5 is now out, let me know if there is anything I can do to help update this YunoHost app!

**Comment by ahstro** [comment]
Noticed 0.10.6 is out soon too (y'all are working fast). I'll try to look into updating this PR when I get some time, but if someone else feels like doing one, go ahead 😊

**Comment by lapineige** [comment]
0.10.6 is out ?
It's not listed here: https://github.com/pixelfed/pixelfed/releases/

edit: Oh ok, it's still a PR, not an official stable version https://github.com/pixelfed/pixelfed/pull/1717

**Comment by StopTrackingUs** [comment]
Tips for fixing the duplication bug from federated status:
1. Run upgrade in debug
2. Copy the postgres login line (if you know the login creds you can skip this)
3. Copy the uri causing the error
4.su root
5.log into postgres
6. Delete the rows in the table "statuses" that has the uri listed in the error

I had to do this multiple times due to 2 comments on the same status duplicated.

**Comment by lapineige** [comment]
I can't run the upgrade command, as it's a Yunohost package, I should not upgrade by the normal process.
I don't know how to log in postgres, neither how to delete anything from here.

**Comment by StopTrackingUs** [comment]
@lapineige yunohost has a command line upgrade process. That is what im refering to.

**Comment by ahstro** [comment]
Updated PR to latest version out now (0.10.6). Sorry about the branch name, but it wasn't editable and I didn't want to close this PR and open a new one on account of the discussion.

**Comment by ahstro** [comment]
Just saw [this toot](https://pleroma.site/notice/9nRAT9gZSapUzefSrY) about `php-intl` being a dependency, so added it now. Works on my testing instance :)

**Comment by yalh76** [comment]
@ahstro Thanks for the help, I was a bit away from coding.

**Comment by yalh76** [comment]
> 
> 
> v0.10.5 is now out, let me know if there is anything I can do to help update this YunoHost app!

Hi @dansup 

Sorry for the time to upgrade Pixelfed. I was a bit discouraged of coding as I was stuck by bugs on other apps.

But no back online ^^

**Comment by ahstro** [comment]
No worries, @yalh76, we all get down periods sometimes. Hope you take care of yourself :pray: :relaxed:

**Comment by lapineige** [comment]
> Tips for fixing the duplication bug from federated status:

>    Run upgrade in debug
>    Copy the postgres login line (if you know the login creds you can skip this)
    Copy the uri causing the error
    4.su root
    5.log into postgres
    Delete the rows in the table "statuses" that has the uri listed in the error

> I had to do this multiple times due to 2 comments on the same status duplicated.

I had to do it multiple times too, that's why I was searching for a more automated way to remove duplicates.
Still the issue seems solved, thanks :)

**Pull request merged**
