### PR TITLE
Fix .env permission (admin panel access to the config file)

### PR DESCRIPTION
**Pull request by lapineige**
#172

### CODE REVIEW

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
Some upgrade fail because of dependencies issues… I suppose that is related to CI and not a real issue ? :thinking:

**Comment by ericgaspar** [comment]
> After being first registered, you need to execute the folloing command to promote first registered as admin
> `$ sudo php7.4 /var/www/pixelfed/artisan user:admin 1`
> and respond yes to the question Add admin privileges to this user?.

Maybe a dumb question but why are we not doing this in the script?

**Comment by lapineige** [comment]
As far as I know, you need to create an user first. Hence we can't do it ourselves.

**Comment by yalh76** [comment]
!testme

**Comment by lapineige** [comment]
!testme

**Pull request merged**
