### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by yalh76**
## Solution
- *Upgrade to 0.9.4*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Validation
---
- [ ] **Code review**
- [ ] **Approval (LGTM)**  
*Code review and approval have to be from a member of @YunoHost/apps group*
- **CI succeeded** : 
[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/pixelfed_ynh_PR61%20(yalh76)/)  

When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by yalh76** [comment]
> package:discover

weird because `php artisan package:discover --ansi` was already present in previous versions...

I have test manual upgrade from 0.9.0 and all was working...

I've added a package_check upgrade from actual master branch, Will wait for the test result.

**Comment by yalh76** [comment]
> 
> 
> I have this issue:
> 
> > Info: Reload the service php7.2-fpm
> > Warning: Script @ php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
> > Warning: Unable to update core dependencies with Composer.
> > Warning: !!
> > Warning:   pixelfed's script has encountered an error. Its execution was cancelled

Have you checked that : https://github.com/capistrano/laravel/issues/50#issuecomment-485172837

**Comment by lapineige** [comment]
`ls config/` :
> app.php           cache.php     dotenv-editor.php  horizon.php          mail.php          queue.php      session.php
auth.php          costar.php    filesystems.php    image-optimizer.php  partialcache.php  recaptcha.php  snowflake.php
backup.php        database.php  hashids.php        image.php            pixelfed.php      routes.php     trustedproxy.php
broadcasting.php  debugbar.php  hashing.php        logging.php          purify.php        services.php   view.php

**Comment by yalh76** [comment]
Seems that there are file missing : https://github.com/pixelfed/pixelfed/tree/v0.9.0/config

like `auth.php` `backup.php`

**Comment by lapineige** [comment]
No they are all here.

**Comment by lapineige** [comment]
A normal upgrade works.
There is an issue with this branch.

**Comment by yalh76** [comment]
> 
> 
> A normal upgrade works.
> There is an issue with this branch.

Very weird... I launched a package_check on two CI:
* [Dev CI](https://ci-apps-dev.yunohost.org/jenkins/job/pixelfed_ynh_PR61%20(yalh76)/3/console) : all is OK
* On my own CI: I have the same error as you have during upgrade from 0.9.0

I will have to do manual upgrade tests and I will let you know

**Comment by lapineige** [comment]
Thanks a lot for your time and work :)

**Comment by yalh76** [comment]
Well seems I found it: https://github.com/pixelfed/pixelfed/releases
Capture

**Comment by yalh76** [comment]
Just push a fix in the testing branch and launch some tests, if you can also test the upgrade ^^

**Comment by lapineige** [comment]
Upgrade works like a charm :)

**Comment by lapineige** [comment]
It's even better: now my Pixelfed federate with Mastodon 🎉
And some


By the way, a Jpeg image of only 1.6MB wasn't uploaded, because of a 413 Request entity too large.
I had to modify Nginx config for pixelfed. I added `client_max_body_size 100M;` in my case.

Maybe we could directly change it here in the repo ?
1.6MB is really tiny for a picture… (even before Pixelfed internal conversion)

**Pull request merged**
