### PR TITLE
Upgrade for v0.10.10

### LINKED ISSUE #125: Update to v.10.10
Pixelfed v.10.10 is out 🙂 https://github.com/pixelfed/pixelfed/releases/tag/v0.10.10

How should we manage the Post Deployment step ? Any idea @yalh76 ?

### PR DESCRIPTION
**Pull request by yalh76**
## Problem
- *Fix #125*

## Solution
- *upgrade for v0.10.10*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

### CODE REVIEW

**Comment by yalh76** [comment]
!testme

**Comment by lapineige** [comment]
Does this needs #127 ?

**Comment by yalh76** [comment]
> 
> 
> Does this needs #127 ?

no, it's not needed, they are independents ^^

**Comment by lapineige** [comment]
Then I would merge #127 first, as it introduces less major changes, that would be easier to debug it if needed.

**Comment by yalh76** [comment]
!testme

**Comment by lapineige** [comment]
By the way, how did you manage the Post Deployment step ?

**Comment by yalh76** [comment]
> 
> 
> By the way, how did you manage the Post Deployment step ?

which one ?
Those ? Yes, they were already on the upgrade steps

```
composer install

php artisan migrate --force

php artisan config:cache

php artisan route:cache

php artisan instance:actor

```

**Comment by lapineige** [comment]
Ok then that's perfect ^^ 💯

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
Own Ci result for Revision: 08ba330c02c89fca8831a23a7155f947690fa923

image

**Pull request merged**
