### PR TITLE
Testing : 0.11.6 (various fixes for v0.11.5 : media/s3/…)

### PR DESCRIPTION
**Pull request by lapineige**
#209 and then v0.11.6 #214 

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by yalh76** [comment]
!testme

**Comment by lapineige** [comment]
It's the very same as https://github.com/YunoHost-Apps/pixelfed_ynh/pull/209#issuecomment-1496224053, nothing change since that time.
So I'm cancelling CI. This needs manual testing.

**Comment by wesleycook74** [comment]
I was finally able to fix this issue on my server by updating to this branch and then setting the filesytem config like so

```
        'local' => [
            'driver' => 'local',
            'root'   => storage_path('app'),
            'permissions' => [
                'file' => [
                    'public' => 0644,
                    'private' => 0660,
                ],
                'dir' => [
                    'public' => 0775,
                    'private' => 0770,
                ],
            ],
        ],
```

**Comment by lapineige** [comment]
> Edit: Nevermind, I was mistaken. It seemed like it was working but not actually.

Too bad :(

**Comment by lapineige** [comment]
This adds improvements while not fixing the image upload bug, so the discussion will continue here, but I'm merging it anyway.

**Pull request merged**
