### PR TITLE
Systemd

### PR DESCRIPTION
**Pull request by ericgaspar**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!tastemetitus

**Comment by ericgaspar** [comment]
!testme

**Comment by lapineige** [comment]
This will probably need intensive testing, with upgrade and fresh install too.

**Comment by yalh76** [comment]
Why removing supervisor ?????

It's the recommendation from laravel https://laravel.com/docs/6.x/horizon#deploying-horizon

**Comment by ericgaspar** [comment]
This is a test. 
The doc doesn't specify a specific task manager to be used with the app.
https://docs.pixelfed.org/running-pixelfed/installation.html#setting-up-services

**Comment by lapineige** [comment]
@ericgaspar shall we delete the branch ? Or keep it for later ?
I don't know why you deleted the branch, I did not follow it that much 😅

**Pull request closed without merging**
