### PR TITLE
4.3

### PR DESCRIPTION
**Pull request by ericgaspar**
- Add config panel
- Upgrade to YNH 4.3
- Add redis_db number
- Add auto updater

### CODE REVIEW

**Comment by ericgaspar** [comment]
!tastemetitus

**Comment by deez17** [comment]
Can someone inform what needs to be done ? 

I’m not a tech guy or an code expert all I know is to instal Yunohost and then add domain and also install pixelfed what else do i need to do to rectify this error on admin panel and also installation ?

**Comment by lapineige** [comment]
For the record, that is a follow-up from that topic : https://forum.yunohost.org/t/pixelfed-installation-error-and-admin-page-cannot-be-accessed/18078/6

@deez17 : please try to install using this URL in the admin interface : https://github.com/YunoHost-Apps/pixelfed_ynh/tree/4.3

**Comment by ericgaspar** [comment]
This PR upgrades the package to last standards. It doesn't particularly adress this [issue](https://forum.yunohost.org/t/pixelfed-installation-error-and-admin-page-cannot-be-accessed/18078/6) (but if it solves it it's good).

**Comment by lapineige** [comment]
As @deez17 described an issue since Yunohost 4.3, I wondered if this would "magically" solves it… that's why I asked if @deez17 could try it :)

**Comment by deez17** [comment]
What do you mean by this link?? All I know is to create a fresh Debian server and install Yunohost on it and select pixelfed undet applications and install it how do I partially install pixelfed and install admin interface from another link ?? 

Sorry this is kinda confusing whatever the fix it is can you please fix it on the Yunohost Pixelfed’s app itself without having partially install from different links ?

or else I request you experts to please provide a step by step  if possible of what needs to be done once again all I know is to only install Yunohost on a Debian server and select pixelfed i have no idea what else should be done

**Comment by deez17** [comment]
> For the record, that is a follow-up from that topic : https://forum.yunohost.org/t/pixelfed-installation-error-and-admin-page-cannot-be-accessed/18078/6
> 
> @deez17 : please try to install using this URL in the admin interface : https://github.com/YunoHost-Apps/pixelfed_ynh/tree/4.3 (if you want to do it with the command line : `yunohost app install https://github.com/YunoHost-Apps/pixelfed_ynh/tree/4.3`)

I’m trying this now

**Comment by Tonyorcl** [comment]
I

> For the record, that is a follow-up from that topic : https://forum.yunohost.org/t/pixelfed-installation-error-and-admin-page-cannot-be-accessed/18078/6
> 
> @deez17 : please try to install using this URL in the admin interface : https://github.com/YunoHost-Apps/pixelfed_ynh/tree/4.3 (if you want to do it with the command line : `yunohost app install https://github.com/YunoHost-Apps/pixelfed_ynh/tree/4.3`)

I tried this in a fresh yunohost install on a fresh Debian 10 server. Still no pixelfed admin console at all and still 419 errors when self signing up on some fresh installs of pixelfed.

**Comment by ericgaspar** [comment]
OK I don't use Pixelfed so I may missed something here.
I am able to install (the fatal git error is not so fatal. the app expects a .git file but we are not installing with git clone so we don't have one)
- I have registered a user
- I have confirmed my account via email
- I have access to the admin

**Comment by deez17** [comment]
Can anyone say what went wrong really?? It was all working fine 3 months ago and all of a sudden I got this your connection is not secure shit messing around when I tried to renew the letsencrypt on Yunohost nothing happened so I had to delete my old Pixelfed which was running well without any issues and create a new one and now I’m facing a terrible issue with not having to instal Pixelfed at all

**Comment by lapineige** [comment]
> can you please fix it on the Yunohost Pixelfed’s app itself

We can't fix a problem that we did/can not diagnose(d).
So first of all I'm trying to check if using this new version would solve your issue. That's why I suggested that you try it, just in case.

About how to do it : in the admin interface → apps → install → at the bottom you can register that URL and install this Pixelfed version.

> Can anyone say what went wrong really??

So far, I can't. I don't have this issue and I am not able to try to install a Pixelfed instance right now.
That's why I will need some feedback from you :)

>  when I tried to renew the letsencrypt on Yunohost nothing happened so I had to delete my old Pixelfed which was running well without any issues and create a new one and now I’m facing a terrible issue with not having to instal Pixelfed at all

That would suggest there is another issue somewhere…
Can you provide full Pixelfed install log ? Here or in the forum (and in private message if you prefer), as you wish.

**Comment by lapineige** [comment]
@Tonyorcl I don't understand what is your issue :sweat_smile:. Can you explain it again please ? And maybe provide any meaningful logs, if you have some.

**Comment by lapineige** [comment]
> In the webadmin I am able to set PHP-config footprint in the config-panel section grinning

@ericgaspar : oh ! I didn't know that came with such a great feature !
We should document this, but this is a great addition :)

**Comment by deez17** [comment]
> > can you please fix it on the Yunohost Pixelfed’s app itself
> 
> We can't fix a problem that we did/can not diagnose(d). So first of all I'm trying to check if using this new version would solve your issue. That's why I suggested that you try it, just in case.
> 
> About how to do it : in the admin interface → apps → install → at the bottom you can register that URL and install this Pixelfed version.
> 
> > Can anyone say what went wrong really??
> 
> So far, I can't. I don't have this issue and I am not able to try to install a Pixelfed instance right now. That's why I will need some feedback from you :)
> 
> > when I tried to renew the letsencrypt on Yunohost nothing happened so I had to delete my old Pixelfed which was running well without any issues and create a new one and now I’m facing a terrible issue with not having to instal Pixelfed at all
> 
> That would suggest there is another issue somewhere… Can you provide full Pixelfed install log ? Here or in the forum (and in private message if you prefer), as you wish.


See this 




and this

**Comment by ericgaspar** [comment]
@deez17 In order to help you, we need proper logs. Screenshots are useless.
You can find the logs in the webadmin -> Tools -> Logs  -> select the one corresponding to pixelfed install and press the green button.
Capture d’écran 1

**Comment by Tonyorcl** [comment]
> @deez17 In order to help you, we need proper logs. Screenshots are useless. You can find the logs in the webadmin -> Tools -> Logs -> select the one corresponding to pixelfed install and press the green button. Capture d’écran 1

https://paste.yunohost.org/raw/rafevitame

**Comment by ericgaspar** [comment]
I can't see anything wrong with the logs.

I am confused, is @deez17 and @deez17 the same person?

**Comment by lapineige** [comment]
@deez17 can you specify what is your issue ?
Pixelfed does not install at all ?

If it does (the log says it does), what's wrong then ?

**Comment by lapineige** [comment]
From the logs
> + ynh_print_warn '--message=The service pixelfed-horizon didn'\''t fully executed the action update before the timeout.'
2021-12-10 12:33:56,671: WARNING -  128769/128769 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%Please wait, the service pixelfed-horizon is updateing..........................................................................................................................................................................................................................................................................................................
2021-12-10 12:33:56,682: DEBUG - + ynh_print_log 'The service pixelfed-horizon didn'\''t fully executed the action update before the timeout.'
2021-12-10 12:33:56,682: DEBUG - + echo -e 'The service pixelfed-horizon didn'\''t fully executed the action update before the timeout.'
2021-12-10 12:33:56,682: WARNING - The service pixelfed-horizon didn't fully executed the action update before the timeout.
2021-12-10 12:33:56,685: DEBUG - + ynh_print_warn '--message=Please find here an extract of the end of the log of the service pixelfed-horizon:'
2021-12-10 12:33:56,695: DEBUG - + ynh_print_log 'Please find here an extract of the end of the log of the service pixelfed-horizon:'
2021-12-10 12:33:56,695: DEBUG - + echo -e 'Please find here an extract of the end of the log of the service pixelfed-horizon:'
2021-12-10 12:33:56,695: WARNING - Please find here an extract of the end of the log of the service pixelfed-horizon:
2021-12-10 12:33:56,696: DEBUG - + ynh_exec_warn journalctl --quiet --no-hostname --no-pager --lines=20 --unit=pixelfed-horizon
2021-12-10 12:33:56,696: DEBUG - + [[ 6 -eq 1 ]]
2021-12-10 12:33:56,696: DEBUG - ++ journalctl --quiet --no-hostname --no-pager --lines=20 --unit=pixelfed-horizon

pixelfed-horizon service seems to have some issue… 🤔

Can you give use the result of that command ? `journalctl --quiet --no-hostname --no-pager --lines=20 --unit=pixelfed-horizon`

**Comment by Tonyorcl** [comment]
My apologies I think I'm posting in the wrong spot.

**Comment by Tonyorcl** [comment]
I thought this was a followup to this topic mentioned above. https://forum.yunohost.org/t/pixelfed-installation-error-and-admin-page-cannot-be-accessed/18078/6

**Comment by deez17** [comment]
Well I’m not interested anymore tired of this thanks everyone for responding giving up Pixelfed

**Comment by lapineige** [comment]
> I thought this was a followup to this topic mentioned above. https://forum.yunohost.org/t/pixelfed-installation-error-and-admin-page-cannot-be-accessed/18078/6

It is :)

**Comment by ericgaspar** [comment]
!tastemetitus

**Review by lapineige — APPROVED** [review]

**Comment by deez17** [comment]
Hi I’m back to know if this is fixed I badly need pixelfed back on fully functional condition to demonstrate one of my project assigned to me any of your experts help is really supportive

**Comment by lapineige** [comment]
Only you can test it… you can use `https://github.com/YunoHost-Apps/pixelfed_ynh/tree/testing` for that (same was as before)

**Comment by deez17** [comment]
Can’t access admin panel it shows something went wrong yet on the testing branch as well

**Comment by lapineige** [comment]
That might means that horizon (the tool used by Pixelfed admin panel) is not working.

I would need to check that, but I don't know what is the easiest way to do it on your side… or how to explain it 😅

Let's try this (don't hesitate to ask if it's not clear):
- log in the command line (SSH)
- install htop if it is not installed `apt install htop`
- then launch it via `htop`
- then press F4 (filter), and enter "horizon" to filter all process running with that in their name/launch command.
- do you see anything ? Such as `php7.3 /var/www/pixelfed/artisan horizon` for instance ?
- If not : maybe try to run `sudo -u pixelfed php7.3 /var/www/pixelfed/artisan horizon`. Does it work ? Can you access admin interface ?

**Comment by deez17** [comment]
I’ll try this 

I’m using an iPhone I don’t have a pc and using Termius to ssh what’s the command to launch htop?

**Comment by lapineige** [comment]
Simply `htop`

**Comment by deez17** [comment]
I tried that and horizon  was started but still sane error

**Comment by lapineige** [comment]
Ok, then I would need some log (located in /var/log/pixelfed or /var/log/horizon I think) to understand what is failing.

**Comment by deez17** [comment]
Is this fixed I’m sorry I’m unable to get logs right now I would like to ask you something additional I’m trying to use laravel forge I have no idea how to use ssh keys as of yet I am only aware of using IP address, port and password to login to ssh 

could you sir please inform me how to access ssh through keys I’m kinda confused it’s a big help to me

**Comment by lapineige** [comment]
> Is this fixed I’m sorry I’m unable to get logs right now

Well I'm asking you for details that would help to fix the issue… If you can't provide them that's ok, but don't ask me to solve an issue that I can't even reproduce or identify :)

About how to use an SSH key: https://yunohost.org/en/security#ssh-authentication-via-key
For additional question, please ask this in Yunohost forum, because 1) you will have plenty more answers there and 2) this is kind of topic :)

**Comment by deez17** [comment]
Horizon started successfully.
[2021-12-14 07:05:52][d7c30d4d-285e-4fab-afc4-53ee9cb42409] Processing: App\$[2021-12-14 07:05:52][d7c30d4d-285e-4fab-afc4-53ee9cb42409] Processed:  App\$[2021-12-14 07:31:09][c0f013d4-afd4-4ca5-8113-dfda901cef1e] Processing: App\$[2021-12-14 07:31:09][c0f013d4-afd4-4ca5-8113-dfda901cef1e] Processed:  App\$Horizon started successfully.

**Comment by deez17** [comment]
Why don’t you instal pixelfed and rectify this issue ? Admin page is not accessible yet

**Comment by lapineige** [comment]
> Horizon started successfully.

Great :)
Hum… did you make yourself an administrator user ? https://github.com/YunoHost-Apps/pixelfed_ynh#administrator


> Why don’t you instal pixelfed and rectify this issue ? Admin page is not accessible yet

Because:
1) I can't reproduce the issue, as I told you.
2) Let's be clear on that thing : I am *not* working for you as an employee or similar. I am a volunteer using its free time to try to improve that package. Don't *ask* me to do something. I'm not your employee. if you are not satisfied by what I am doing, do it yourself.

**Comment by bcye** [comment]
Hi @lapineige,

I'm getting this issue as well.
the `fatal: not a .git repository` happens after `artisan update`. later on the pixelfed-horizon service timeous and I'm guessing this is the reason why it's stalling in the gui.

Pixelfed works fine (but without federation) after the installation and commands listed in the readme. When I try to access the admin panel of pixelfed (I am an admin user), Pixelfed says something went wrong (e.g. server error).

[Here are my full logs](https://paste.yunohost.org/raw/ucizoronoj) for further debugging.

Hope we can get this fixed.

**Comment by lapineige** [comment]
I wonder if #157 would solve this :thinking:
Can any of you test it ?

> the fatal: not a .git repository happens after artisan update. later on the pixelfed-horizon service timeous and I'm guessing this is the reason why it's stalling in the gui.

That should only be a simple warning with no implications, as far as I understand…

**Comment by bcye** [comment]
> I wonder if #157 would solve this :thinking:
> 
> Can any of you test it ?
> 
> 
> 
> > the fatal: not a .git repository happens after artisan update. later on the pixelfed-horizon service timeous and I'm guessing this is the reason why it's stalling in the gui.
> 
> 
> 
> That should only be a simple warning with no implications, as far as I understand…
> 
> 

Will try it tomorrow, thanks!

**Comment by bcye** [comment]
@lapineige i did a completely fresh install with a .noho.st domain on a Debian 10 Hetzner VPS and could replicate the issue. How do I install the app from the PR?

**Comment by bcye** [comment]
Nevermind, I installed it from the systemd branch with help from the developer info in the readme.
Admin page still doesn't load.

**Comment by bcye** [comment]
Here's the log from that install https://paste.yunohost.org/raw/padibevoqe

**Comment by lapineige** [comment]
I don't see anything special…
I suppose we should investigate Pixelfed / Horizon / PHP logs… For now I have no idea of the origin of that issue :(

**Comment by bcye** [comment]
> I don't see anything special…
> 
> I suppose we should investigate Pixelfed / Horizon / PHP logs… For now I have no idea of the origin of that issue :(

There are (I think base64) encoded diagnostic details that the error site offers to copy.

**Comment by lapineige** [comment]
What do you mean ? On the paste you shared ?

**Comment by bcye** [comment]
image

This what it looks like.

It returns the following b64:
```

eyJpdiI6IkJ0bDJlemtFMUp2Z3pHOFJvcTBLZHc9PSIsInZhbHVlIjoiUkZzNGZmU0FhNG9wZ1o1R1BiMGFnN043NzBMSTVkRDEzK0g3b3NLc1A4ckRpYVRNT3dEaDFJSll1Vms1Smh3WFZwZHI5bC9oMStKMzQ5U2ViK0NpU3RvN2dka0NPMFl3RHI0V096Tzk2dkhiKzVKaStpanNhQjNvUDZxc1pMMitMRU5xaHFXUm1kaVZsZDNIS3c5NWc4T2J4SXR0WTBRQktUT25ldnBwcHh1Rm55aGFTMnRVWmkyeHRrTEd0dGQ1RWRXZ0VCMERscGRGMy8za1RHWVg3cHNIWlFuTHZyelNJT201Qm5XZDVQQzJKMHhtc1ZiNitxMWdHazNzNnh5MGhJdU5rUUFwL1U4SnJ5bnAwbFdBSkw4YzdWcW1GRjVqTzd3RWd4RlpDMHRJRXBnMStzL2U1TXF4aFp3TzducS9FOHFFdTRqdGVTVmh1NE10K01mNDJicERmNFJRdU1YdG8zRVBhb21EWURlQjBVTnpjbCtzSkVTdVFKeC9EZDVJc1VzbXgxZnBVbE5UQncrSFNOVVFIKzBja01najlhTmZjZ0pNTDlOWC83Z1EzU2o1azZ0bm1RbG1QNU4ydG5qS2twY1RMbXlNYU1wendmZ2JxeGdJRUFxNTNmYTFGVklrSzVNZHJCSXZjRHFka3lvY1locHRXSURiUWkrUmJZblR0NmVYZEtaN3IzRGtZSjZDNjBaOHlhdHF4UVk0SkNENy9RREJOVEZtZS9qZmREYjMrQ0w1cHhaSDRCQW53a09wZlFRc3FnY2hkTE90WHlBVHh2c3QxNlovVm9iZTI4VG95SWkzQ29jdnAweUdhcGlpZ3d2OGFjNkhjcTdKanZaQzNMS1dFKzdJWllkV3ZrZHFZV3UyTTZvOElYeGVyclB0cXRTUmxadmhTdTZYWjA5UDZxMzJ6WTRhdlRqK1AzemJrK20xSytJeWxyK1ZZSkI3SWtTM0dBPT0iLCJtYWMiOiI3ZjE5MTRiOWEwMThmNThjZDJkYmZkZWQ2NTYyOWZiNzQxN2RjYTVhZGQ3Y2Q1N2QxNDI1NTkzZmNkYmFiY2FlIn0=
```

This decodes into:
```

{"iv":"Btl2ezkE1JvgzG8Roq0Kdw==","value":"RFs4ffSAa4opgZ5GPb0ag7N770LI5dD13+H7osKsP8rDiaTMOwDh1IJYuVk5JhwXVpdr9l/h1+J349Seb+CiSto7gdkCO0YwDr4WOzO96vHb+5Ji+ijsaB3oP6qsZL2+LENqhqWRmdiVld3HKw95g8ObxIttY0QBKTOnevpppxuFnyhaS2tUZi2xtkLGttd5EdWgEB0DlpdF3/3kTGYX7psHZQnLvrzSIOm5BnWd5PC2J0xmsVb6+q1gGk3s6xy0hIuNkQAp/U8Jrynp0lWAJL8c7VqmFF5jO7wEgxFZC0tIEpg1+s/e5MqxhZwO7nq/E8qEu4jteSVhu4Mt+Mf42bpDf4RQuMXto3EPaomDYDeB0UNzcl+sJESuQJx/Dd5IsUsmx1fpUlNTBw+HSNUQH+0ckMgj9aNfcgJML9NX/7gQ3Sj5k6tnmQlmP5N2tnjKkpcTLmyMaMpzwfgbqxgIEAq53fa1FVIkK5MdrBIvcDqdkyocYhptWIDbQi+RbYnTt6eXdKZ7r3DkYJ6C60Z8yatqxQY4JCD7/QDBNTFme/jfdDb3+CL5pxZH4BAnwkOpfQQsqgchdLOtXyATxvst16Z/Vobe28ToyIi3Cocvp0yGapiigwv8ac6Hcq7JjvZC3LKWE+7IZYdWvkdqYWu2M6o8IXxerrPtqtSRlZvhSu6XZ09P6q32zY4avTj+P3zbk+m1K+Iylr+VYJB7IkS3GA==","mac":"7f1914b9a018f58cd2dbfded65629fb7417dca5add7cd57d1425593fcdbabcae"}
```

Pasting the values into a decoder doesn't return anything usable though.

**Comment by lapineige** [comment]
Thank you for investigating this. Maybe can you try `php7.3 artisan config:cache` ? (from pixelfed folder)
I wonder if we should ask for advice to Pixelfed dev team… I don't know if it's a Yunohost specific problem (but I think so), but at least I don't know where and what to search for…

**Comment by bcye** [comment]
That doesn't work sadly. If you're sure artisan update isn't causing the issue, we debugged supervisor if I understood #157 correctly, then it shouldn't be related to the yunohost install process specifically. Probably worth it to ask them, or figure out what the b64 is about, though I found nothing on that.

**Comment by lapineige** [comment]
It's a bit of a blind shot, but what you could try is to install an old version (I don't know, like a year old version or something like that ?), see if the issue is happening, and then try to upgrade to the latest version. Maybe we broke something during updates ?

What is strange is that I can't reproduce it on a fresh install.

**Comment by bcye** [comment]
@lapineige what system where you using for the fresh install, because i could replicate it.

I used debian 10 hetzner lowest tier, only roundcube and pixelfed uninstalled and reinstalled again. dyndns via noho.st

**Comment by bcye** [comment]
though the issues where happening before i uninstalled it as well

**Comment by lapineige** [comment]
I tried on a very standard x86 VPS, using debian 10 for the fresh install.
I migrated my own instance to an hetzner lowest tier too a while ago, no change.

I'll try on a raspberry pi, just in case.

**Comment by lapineige** [comment]
I can reproduce the issue. I have a base64 error log too, but I don't know how to decode it.

**Comment by bcye** [comment]
Ok I found it, the website should be pixelfed-debug.com but it returns an SSL error. Luckily it is open source, the repo is https://github.com/pixelfedLabs/pixelfed-debug and the decoder is an html file. I'm on mobile right now and will try it later.

**Comment by lapineige** [comment]
And that's easy to install in a Custom Webapp package :tada:
I signalled to the author the issue with the official website.

**Comment by lapineige** [comment]
Apparently there is a fix (or rather a workaround): https://github.com/YunoHost-Apps/pixelfed_ynh/issues/160#issuecomment-1007095382

**Comment by bcye** [comment]
Awesome!

**Pull request merged**
