### PR TITLE
v0.11.2 + change php version to 7.4

### PR DESCRIPTION
**Pull request by lapineige**
## Problem

- A new Pixelfed version is available : v0.11.2 https://github.com/pixelfed/pixelfed/releases/tag/v0.11.2
- Php 7.3 is no longer supported https://github.com/pixelfed/pixelfed/pull/3041

## Solution

- Upgrade Pixelfed
- Switch to php 7.4

## PR Status

**Pending until Pixelfed version is released** : I wanted to keep in mind that we would need to upgrade PHP version… that's why I made that draft

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)
- [x] Upgrade from previous installation (using php7.3) as been tested

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by lapineige** [comment]
!testme

**Review by yalh76 — APPROVED** [review]
Adding a check from actual 0.11.1~ynh2 would be great

**Comment by lapineige** [comment]
I don't understand.

(also CI failing, an issue with php7.4 ?)

**Comment by yalh76** [comment]
> I don't understand.
Done at https://github.com/YunoHost-Apps/pixelfed_ynh/pull/159/commits/9f255da5a4a21a7597d6405479fe9cbad18a1e31

> 
> (also CI failing, an issue with php7.4 ?)
It's just because php-fpm is restored before dependencies

**Comment by yalh76** [comment]
!testme

**Comment by lapineige** [comment]
For my culture, what's the use of that check ?

**Comment by lapineige** [comment]
So:
The PHP version used is php7.3 because it's the settings stored for the app in Yunohost settings, not this repository:  https://github.com/YunoHost-Apps/pixelfed_ynh/blob/new-PF-version/scripts/upgrade#L28

Should we force it to use the new version https://github.com/YunoHost-Apps/pixelfed_ynh/blob/new-PF-version/scripts/_common.sh#L7 ?

The second issue is PHP extension bcmath missing. We set it here https://github.com/YunoHost-Apps/pixelfed_ynh/blob/new-PF-version/scripts/_common.sh#L11, but I guess that's not the good version ?

@YunoHost-Apps/apps-group I think I will need help to make that app able to upgrade php version on the fly while installing, I don't know what I'm doing here… I would probably miss something 😅 🙏

**Comment by yalh76** [comment]
!testme

**Comment by lapineige** [comment]
I tried it, no luck :sweat_smile:

> Info: DEBUG - + update-alternatives --set php /usr/bin/php7.3
Info: DEBUG - + ynh_app_setting_set --app=pixelfed --key=phpversion --value=7.4
Info: DEBUG - + local _globalapp=pixelfed
Info: DEBUG - + app=pixelfed
Info: DEBUG - + [[ phpversion =~ (unprotected|protected|skipped)_ ]]
Info: DEBUG - + ynh_app_setting set pixelfed phpversion 7.4
Info: DEBUG - /usr/share/yunohost/helpers.d/apt: line 328: phpversion: unbound variable

**Comment by yalh76** [comment]
> update-alternatives

I don't understand when it happens, can you provide a yunopaste of the full logs ?

**Comment by lapineige** [comment]
I update my comment with more detailed log, sorry the log given by Yunohost was too short.

**Comment by yalh76** [comment]
!testme

**Comment by lapineige** [comment]
*I took the liberty to cancel the previous CI*

It failed ! 😅

```
2022-01-14 21:41:09,687: INFO - [#####...............] > Upgrading PHP-FPM configuration...
2022-01-14 21:41:09,772: DEBUG - + package=
2022-01-14 21:41:09,772: DEBUG - + use_template=1
2022-01-14 21:41:09,772: DEBUG - + usage=low
2022-01-14 21:41:09,772: DEBUG - + footprint=low
2022-01-14 21:41:09,772: DEBUG - + '[' -n low ']'
2022-01-14 21:41:09,772: DEBUG - + use_template=0
2022-01-14 21:41:09,772: DEBUG - + dedicated_service=0
2022-01-14 21:41:09,772: DEBUG - + phpversion=7.4
2022-01-14 21:41:09,773: DEBUG - ++ ynh_app_setting_get --app=pixelfed --key=phpversion
2022-01-14 21:41:09,774: DEBUG - ++ local _globalapp=pixelfed
2022-01-14 21:41:09,820: DEBUG - ++ app=pixelfed
2022-01-14 21:41:09,820: DEBUG - ++ [[ phpversion =~ (unprotected|protected|skipped)_ ]]
2022-01-14 21:41:09,820: DEBUG - ++ ynh_app_setting get pixelfed phpversion
2022-01-14 21:41:09,864: DEBUG - + local old_phpversion=7.3
2022-01-14 21:41:09,864: DEBUG - + '[' -n 7.3 ']'
2022-01-14 21:41:09,864: DEBUG - + '[' 7.3 '!=' 7.4 ']'
2022-01-14 21:41:09,865: DEBUG - ++ ynh_app_setting_get --app=pixelfed --key=fpm_config_dir
2022-01-14 21:41:09,865: DEBUG - ++ local _globalapp=pixelfed
2022-01-14 21:41:09,895: DEBUG - ++ app=pixelfed
2022-01-14 21:41:09,895: DEBUG - ++ [[ fpm_config_dir =~ (unprotected|protected|skipped)_ ]]
2022-01-14 21:41:09,896: DEBUG - ++ ynh_app_setting get pixelfed fpm_config_dir
2022-01-14 21:41:09,939: DEBUG - + local old_php_fpm_config_dir=/etc/php/7.3/fpm
2022-01-14 21:41:09,939: DEBUG - + local old_php_finalphpconf=/etc/php/7.3/fpm/pool.d/pixelfed.conf
2022-01-14 21:41:09,940: DEBUG - + [[ -f /etc/php/7.3/fpm/pool.d/pixelfed.conf ]]
2022-01-14 21:41:09,940: DEBUG - + ynh_backup_if_checksum_is_different --file=/etc/php/7.3/fpm/pool.d/pixelfed.conf
2022-01-14 21:41:09,949: DEBUG - + local checksum_setting_name=checksum__etc_php_7.3_fpm_pool.d_pixelfed.conf
2022-01-14 21:41:09,950: DEBUG - ++ ynh_app_setting_get --app=pixelfed --key=checksum__etc_php_7.3_fpm_pool.d_pixelfed.conf
2022-01-14 21:41:09,950: DEBUG - ++ local _globalapp=pixelfed
2022-01-14 21:41:09,982: DEBUG - ++ app=pixelfed
2022-01-14 21:41:09,982: DEBUG - ++ [[ checksum__etc_php_7.3_fpm_pool.d_pixelfed.conf =~ (unprotected|protected|skipped)_ ]]
2022-01-14 21:41:09,982: DEBUG - ++ ynh_app_setting get pixelfed checksum__etc_php_7.3_fpm_pool.d_pixelfed.conf
2022-01-14 21:41:10,030: DEBUG - + local checksum_value=8c60406d30e16fa1cf346bc90c49c6bc
2022-01-14 21:41:10,030: DEBUG - + backup_file_checksum=
2022-01-14 21:41:10,030: DEBUG - + '[' -n 8c60406d30e16fa1cf346bc90c49c6bc ']'
2022-01-14 21:41:10,031: DEBUG - + '[' -e /etc/php/7.3/fpm/pool.d/pixelfed.conf ']'
2022-01-14 21:41:10,031: DEBUG - + md5sum --check --status
2022-01-14 21:41:10,033: DEBUG - + ynh_remove_fpm_config
2022-01-14 21:41:10,034: DEBUG - ++ ynh_app_setting_get --app=pixelfed --key=fpm_config_dir
2022-01-14 21:41:10,034: DEBUG - ++ local _globalapp=pixelfed
2022-01-14 21:41:10,066: DEBUG - ++ app=pixelfed
2022-01-14 21:41:10,067: DEBUG - ++ [[ fpm_config_dir =~ (unprotected|protected|skipped)_ ]]
2022-01-14 21:41:10,067: DEBUG - ++ ynh_app_setting get pixelfed fpm_config_dir
2022-01-14 21:41:10,112: DEBUG - + local fpm_config_dir=/etc/php/7.3/fpm
2022-01-14 21:41:10,113: DEBUG - ++ ynh_app_setting_get --app=pixelfed --key=fpm_service
2022-01-14 21:41:10,113: DEBUG - ++ local _globalapp=pixelfed
2022-01-14 21:41:10,146: DEBUG - ++ app=pixelfed
2022-01-14 21:41:10,147: DEBUG - ++ [[ fpm_service =~ (unprotected|protected|skipped)_ ]]
2022-01-14 21:41:10,147: DEBUG - ++ ynh_app_setting get pixelfed fpm_service
2022-01-14 21:41:10,192: DEBUG - + local fpm_service=php7.3-fpm
2022-01-14 21:41:10,192: DEBUG - ++ ynh_app_setting_get --app=pixelfed --key=fpm_dedicated_service
2022-01-14 21:41:10,193: DEBUG - ++ local _globalapp=pixelfed
2022-01-14 21:41:10,224: DEBUG - ++ app=pixelfed
2022-01-14 21:41:10,224: DEBUG - ++ [[ fpm_dedicated_service =~ (unprotected|protected|skipped)_ ]]
2022-01-14 21:41:10,224: DEBUG - ++ ynh_app_setting get pixelfed fpm_dedicated_service
2022-01-14 21:41:10,269: DEBUG - + local dedicated_service=0
2022-01-14 21:41:10,269: DEBUG - + dedicated_service=0
2022-01-14 21:41:10,270: DEBUG - ++ ynh_app_setting_get --app=pixelfed --key=phpversion
2022-01-14 21:41:10,270: DEBUG - ++ local _globalapp=pixelfed
2022-01-14 21:41:10,301: DEBUG - ++ app=pixelfed
2022-01-14 21:41:10,302: DEBUG - ++ [[ phpversion =~ (unprotected|protected|skipped)_ ]]
2022-01-14 21:41:10,302: DEBUG - ++ ynh_app_setting get pixelfed phpversion
2022-01-14 21:41:10,348: DEBUG - + local phpversion=7.3
2022-01-14 21:41:10,348: DEBUG - + phpversion=7.3
2022-01-14 21:41:10,348: DEBUG - + '[' -z /etc/php/7.3/fpm ']'
2022-01-14 21:41:10,348: DEBUG - + ynh_secure_remove --file=/etc/php/7.3/fpm/pool.d/pixelfed.conf
2022-01-14 21:41:10,369: DEBUG - + '[' -e /etc/php/7.3/fpm/conf.d/20-pixelfed.ini ']'
2022-01-14 21:41:10,369: DEBUG - + ynh_package_is_installed --package=php7.3-fpm
2022-01-14 21:41:10,381: DEBUG - + ynh_wait_dpkg_free
2022-01-14 21:41:10,479: DEBUG - + return 0
2022-01-14 21:41:10,480: DEBUG - + grep --count 'ok installed'
2022-01-14 21:41:10,481: DEBUG - + dpkg-query --show '--showformat=${Status}' php7.3-fpm
2022-01-14 21:41:10,499: DEBUG - + ynh_systemd_action --service_name=php7.3-fpm --action=reload
2022-01-14 21:41:10,573: DEBUG - + service_name=php7.3-fpm
2022-01-14 21:41:10,573: DEBUG - + action=reload
2022-01-14 21:41:10,573: DEBUG - + line_match=
2022-01-14 21:41:10,573: DEBUG - + length=20
2022-01-14 21:41:10,573: DEBUG - + log_path=/var/log/php7.3-fpm/php7.3-fpm.log
2022-01-14 21:41:10,573: DEBUG - + timeout=300
2022-01-14 21:41:10,573: DEBUG - + '[' reload == stop ']'
2022-01-14 21:41:10,573: DEBUG - + '[' reload == reload ']'
2022-01-14 21:41:10,573: DEBUG - + action=reload-or-restart
2022-01-14 21:41:10,573: DEBUG - + systemctl reload-or-restart php7.3-fpm
2022-01-14 21:41:10,596: DEBUG - + '[' 7.3 '!=' 7.3 ']'
2022-01-14 21:41:10,596: DEBUG - + '[' -n '' ']'
2022-01-14 21:41:10,597: DEBUG - + local fpm_service=php7.4-fpm
2022-01-14 21:41:10,597: DEBUG - + local fpm_config_dir=/etc/php/7.4/fpm
2022-01-14 21:41:10,597: DEBUG - + mkdir --parents /etc/php/7.4/fpm/pool.d
2022-01-14 21:41:10,604: DEBUG - + ynh_app_setting_set --app=pixelfed --key=fpm_config_dir --value=/etc/php/7.4/fpm
2022-01-14 21:41:10,604: DEBUG - + local _globalapp=pixelfed
2022-01-14 21:41:10,754: DEBUG - + app=pixelfed
2022-01-14 21:41:10,754: DEBUG - + [[ fpm_config_dir =~ (unprotected|protected|skipped)_ ]]
2022-01-14 21:41:10,754: DEBUG - + ynh_app_setting set pixelfed fpm_config_dir /etc/php/7.4/fpm
2022-01-14 21:41:10,805: DEBUG - + ynh_app_setting_set --app=pixelfed --key=fpm_service --value=php7.4-fpm
2022-01-14 21:41:10,805: DEBUG - + local _globalapp=pixelfed
2022-01-14 21:41:10,868: DEBUG - + app=pixelfed
2022-01-14 21:41:10,868: DEBUG - + [[ fpm_service =~ (unprotected|protected|skipped)_ ]]
2022-01-14 21:41:10,868: DEBUG - + ynh_app_setting set pixelfed fpm_service php7.4-fpm
2022-01-14 21:41:10,918: DEBUG - + ynh_app_setting_set --app=pixelfed --key=fpm_dedicated_service --value=0
2022-01-14 21:41:10,918: DEBUG - + local _globalapp=pixelfed
2022-01-14 21:41:10,982: DEBUG - + app=pixelfed
2022-01-14 21:41:10,983: DEBUG - + [[ fpm_dedicated_service =~ (unprotected|protected|skipped)_ ]]
2022-01-14 21:41:10,983: DEBUG - + ynh_app_setting set pixelfed fpm_dedicated_service 0
2022-01-14 21:41:11,030: DEBUG - + ynh_app_setting_set --app=pixelfed --key=phpversion --value=7.4
2022-01-14 21:41:11,031: DEBUG - + local _globalapp=pixelfed
2022-01-14 21:41:11,107: DEBUG - + app=pixelfed
2022-01-14 21:41:11,107: DEBUG - + [[ phpversion =~ (unprotected|protected|skipped)_ ]]
2022-01-14 21:41:11,107: DEBUG - + ynh_app_setting set pixelfed phpversion 7.4
2022-01-14 21:41:11,156: DEBUG - + ynh_app_setting_set --app=pixelfed --key=fpm_footprint --value=low
2022-01-14 21:41:11,156: DEBUG - + local _globalapp=pixelfed
2022-01-14 21:41:11,221: DEBUG - + app=pixelfed
2022-01-14 21:41:11,222: DEBUG - + [[ fpm_footprint =~ (unprotected|protected|skipped)_ ]]
2022-01-14 21:41:11,222: DEBUG - + ynh_app_setting set pixelfed fpm_footprint low
2022-01-14 21:41:11,270: DEBUG - + ynh_app_setting_set --app=pixelfed --key=fpm_usage --value=low
2022-01-14 21:41:11,271: DEBUG - + local _globalapp=pixelfed
2022-01-14 21:41:11,335: DEBUG - + app=pixelfed
2022-01-14 21:41:11,335: DEBUG - + [[ fpm_usage =~ (unprotected|protected|skipped)_ ]]
2022-01-14 21:41:11,335: DEBUG - + ynh_app_setting set pixelfed fpm_usage low
2022-01-14 21:41:11,388: DEBUG - + ynh_get_scalable_phpfpm --usage=low --footprint=low
2022-01-14 21:41:11,435: DEBUG - + footprint=low
2022-01-14 21:41:11,436: DEBUG - + usage=low
2022-01-14 21:41:11,436: DEBUG - + print=0
2022-01-14 21:41:11,436: DEBUG - + '[' low = low ']'
2022-01-14 21:41:11,436: DEBUG - + footprint=20
2022-01-14 21:41:11,436: DEBUG - + '[' 20 -le 20 ']'
2022-01-14 21:41:11,436: DEBUG - + min_spare_servers_factor=8
2022-01-14 21:41:11,436: DEBUG - + '[' low = low ']'
2022-01-14 21:41:11,436: DEBUG - + php_pm=ondemand
2022-01-14 21:41:11,437: DEBUG - ++ ynh_get_ram --total --ignore_swap
2022-01-14 21:41:11,488: DEBUG - ++ ignore_swap=1
2022-01-14 21:41:11,488: DEBUG - ++ only_swap=0
2022-01-14 21:41:11,488: DEBUG - ++ free=0
2022-01-14 21:41:11,488: DEBUG - ++ total=1
2022-01-14 21:41:11,489: DEBUG - +++ awk '{print $1}'
2022-01-14 21:41:11,492: DEBUG - +++ grep 'total memory'
2022-01-14 21:41:11,494: DEBUG - +++ vmstat --stats --unit M
2022-01-14 21:41:11,500: DEBUG - ++ local total_ram=1947
2022-01-14 21:41:11,502: DEBUG - +++ awk '{print $1}'
2022-01-14 21:41:11,505: DEBUG - +++ grep 'total swap'
2022-01-14 21:41:11,506: DEBUG - +++ vmstat --stats --unit M
2022-01-14 21:41:11,511: DEBUG - ++ local total_swap=3894
2022-01-14 21:41:11,511: DEBUG - ++ local total_ram_swap=5841
2022-01-14 21:41:11,511: DEBUG - ++ local ram=5841
2022-01-14 21:41:11,512: DEBUG - ++ ram=1947
2022-01-14 21:41:11,512: DEBUG - ++ echo 1947
2022-01-14 21:41:11,512: DEBUG - + local max_ram=1947
2022-01-14 21:41:11,512: DEBUG - + php_max_children=48
2022-01-14 21:41:11,512: DEBUG - + '[' ondemand = static ']'
2022-01-14 21:41:11,513: DEBUG - ++ at_least_one 48
2022-01-14 21:41:11,513: DEBUG - ++ '[' 48 -le 0 ']'
2022-01-14 21:41:11,514: DEBUG - ++ echo 48
2022-01-14 21:41:11,515: DEBUG - + php_max_children=48
2022-01-14 21:41:11,515: DEBUG - ++ nproc
2022-01-14 21:41:11,518: DEBUG - + local core_number=1
2022-01-14 21:41:11,518: DEBUG - + local max_proc=4
2022-01-14 21:41:11,518: DEBUG - + '[' 48 -gt 4 ']'
2022-01-14 21:41:11,518: DEBUG - + php_max_children=4
2022-01-14 21:41:11,519: DEBUG - ++ ynh_app_setting_get --app=pixelfed --key=php_forced_max_children
2022-01-14 21:41:11,519: DEBUG - ++ local _globalapp=pixelfed
2022-01-14 21:41:11,554: DEBUG - ++ app=pixelfed
2022-01-14 21:41:11,554: DEBUG - ++ [[ php_forced_max_children =~ (unprotected|protected|skipped)_ ]]
2022-01-14 21:41:11,554: DEBUG - ++ ynh_app_setting get pixelfed php_forced_max_children
2022-01-14 21:41:11,600: DEBUG - + local php_forced_max_children=
2022-01-14 21:41:11,600: DEBUG - + '[' -n '' ']'
2022-01-14 21:41:11,600: DEBUG - + '[' ondemand = dynamic ']'
2022-01-14 21:41:11,600: DEBUG - + php_min_spare_servers=0
2022-01-14 21:41:11,601: DEBUG - + php_max_spare_servers=0
2022-01-14 21:41:11,601: DEBUG - + php_start_servers=0
2022-01-14 21:41:11,601: DEBUG - + local phpfpm_path=/var/cache/yunohost/app_tmp_work_dirs/app_uzn7fp17/conf/php-fpm.conf
2022-01-14 21:41:11,601: DEBUG - [__APP__]
2022-01-14 21:41:11,601: DEBUG - 
2022-01-14 21:41:11,601: DEBUG - user = __APP__
2022-01-14 21:41:11,601: DEBUG - group = __APP__
2022-01-14 21:41:11,601: DEBUG - 
2022-01-14 21:41:11,601: DEBUG - chdir = __FINALPATH__
2022-01-14 21:41:11,601: DEBUG - 
2022-01-14 21:41:11,601: DEBUG - listen = /var/run/php/php__PHPVERSION__-fpm-__APP__.sock
2022-01-14 21:41:11,601: DEBUG - listen.owner = www-data
2022-01-14 21:41:11,601: DEBUG - listen.group = www-data
2022-01-14 21:41:11,601: DEBUG - 
2022-01-14 21:41:11,601: DEBUG - pm = __PHP_PM__
2022-01-14 21:41:11,601: DEBUG - pm.max_children = __PHP_MAX_CHILDREN__
2022-01-14 21:41:11,602: DEBUG - pm.max_requests = 500
2022-01-14 21:41:11,602: DEBUG - request_terminate_timeout = 1d
2022-01-14 21:41:11,602: DEBUG - '
2022-01-14 21:41:11,602: DEBUG - + '[' ondemand = dynamic ']'
2022-01-14 21:41:11,602: DEBUG - + '[' ondemand = ondemand ']'
2022-01-14 21:41:11,602: DEBUG - pm.process_idle_timeout = 10s
2022-01-14 21:41:11,602: DEBUG - '
2022-01-14 21:41:11,602: DEBUG - + '[' -e /var/cache/yunohost/app_tmp_work_dirs/app_uzn7fp17/conf/extra_php-fpm.conf ']'
2022-01-14 21:41:11,602: DEBUG - + local finalphpconf=/etc/php/7.4/fpm/pool.d/pixelfed.conf
2022-01-14 21:41:11,602: DEBUG - + ynh_add_config --template=/var/cache/yunohost/app_tmp_work_dirs/app_uzn7fp17/conf/php-fpm.conf --destination=/etc/php/7.4/fpm/pool.d/pixelfed.conf
2022-01-14 21:41:11,632: DEBUG - + '[' -f /var/cache/yunohost/app_tmp_work_dirs/app_uzn7fp17/conf//var/cache/yunohost/app_tmp_work_dirs/app_uzn7fp17/conf/php-fpm.conf ']'
2022-01-14 21:41:11,632: DEBUG - + '[' -f /var/cache/yunohost/app_tmp_work_dirs/app_uzn7fp17/conf/php-fpm.conf ']'
2022-01-14 21:41:11,632: DEBUG - + template_path=/var/cache/yunohost/app_tmp_work_dirs/app_uzn7fp17/conf/php-fpm.conf
2022-01-14 21:41:11,632: DEBUG - + ynh_backup_if_checksum_is_different --file=/etc/php/7.4/fpm/pool.d/pixelfed.conf
2022-01-14 21:41:11,642: DEBUG - + local checksum_setting_name=checksum__etc_php_7.4_fpm_pool.d_pixelfed.conf
2022-01-14 21:41:11,643: DEBUG - ++ ynh_app_setting_get --app=pixelfed --key=checksum__etc_php_7.4_fpm_pool.d_pixelfed.conf
2022-01-14 21:41:11,643: DEBUG - ++ local _globalapp=pixelfed
2022-01-14 21:41:11,674: DEBUG - ++ app=pixelfed
2022-01-14 21:41:11,674: DEBUG - ++ [[ checksum__etc_php_7.4_fpm_pool.d_pixelfed.conf =~ (unprotected|protected|skipped)_ ]]
2022-01-14 21:41:11,674: DEBUG - ++ ynh_app_setting get pixelfed checksum__etc_php_7.4_fpm_pool.d_pixelfed.conf
2022-01-14 21:41:11,721: DEBUG - + local checksum_value=
2022-01-14 21:41:11,721: DEBUG - + backup_file_checksum=
2022-01-14 21:41:11,721: DEBUG - + '[' -n '' ']'
2022-01-14 21:41:11,721: DEBUG - + touch /etc/php/7.4/fpm/pool.d/pixelfed.conf
2022-01-14 21:41:11,722: DEBUG - + chown root:root /etc/php/7.4/fpm/pool.d/pixelfed.conf
2022-01-14 21:41:11,724: DEBUG - + chmod 640 /etc/php/7.4/fpm/pool.d/pixelfed.conf
2022-01-14 21:41:11,725: DEBUG - + cp -f /var/cache/yunohost/app_tmp_work_dirs/app_uzn7fp17/conf/php-fpm.conf /etc/php/7.4/fpm/pool.d/pixelfed.conf
2022-01-14 21:41:11,726: DEBUG - + _ynh_apply_default_permissions /etc/php/7.4/fpm/pool.d/pixelfed.conf
2022-01-14 21:41:11,726: DEBUG - + local target=/etc/php/7.4/fpm/pool.d/pixelfed.conf
2022-01-14 21:41:11,727: DEBUG - ++ tr -d '>= '
2022-01-14 21:41:11,729: DEBUG - ++ jq -r .requirements.yunohost /var/cache/yunohost/app_tmp_work_dirs/app_uzn7fp17/manifest.json
2022-01-14 21:41:11,733: DEBUG - + local ynh_requirement=4.3.0
2022-01-14 21:41:11,733: DEBUG - + '[' -z 4.3.0 ']'
2022-01-14 21:41:11,733: DEBUG - + '[' 4.3.0 == null ']'
2022-01-14 21:41:11,733: DEBUG - + dpkg --compare-versions 4.3.0 ge 4.2
2022-01-14 21:41:11,736: DEBUG - + chmod o-rwx /etc/php/7.4/fpm/pool.d/pixelfed.conf
2022-01-14 21:41:11,737: DEBUG - + chmod g-w /etc/php/7.4/fpm/pool.d/pixelfed.conf
2022-01-14 21:41:11,738: DEBUG - + chown -R root:root /etc/php/7.4/fpm/pool.d/pixelfed.conf
2022-01-14 21:41:11,740: DEBUG - + ynh_system_user_exists pixelfed
2022-01-14 21:41:11,750: DEBUG - + getent passwd pixelfed
2022-01-14 21:41:11,752: DEBUG - + chown pixelfed:pixelfed /etc/php/7.4/fpm/pool.d/pixelfed.conf
2022-01-14 21:41:11,753: DEBUG - + ynh_replace_vars --file=/etc/php/7.4/fpm/pool.d/pixelfed.conf
2022-01-14 21:41:11,764: DEBUG - + test -n /
2022-01-14 21:41:11,764: DEBUG - + local path_url_slash_less=
2022-01-14 21:41:11,764: DEBUG - + ynh_replace_string --match_string=__PATH__/ --replace_string=/ --target_file=/etc/php/7.4/fpm/pool.d/pixelfed.conf
2022-01-14 21:41:11,826: DEBUG - + sed --in-place s@__PATH__/@/@g /etc/php/7.4/fpm/pool.d/pixelfed.conf
2022-01-14 21:41:11,828: DEBUG - + ynh_replace_string --match_string=__PATH__ --replace_string=/ --target_file=/etc/php/7.4/fpm/pool.d/pixelfed.conf
2022-01-14 21:41:11,895: DEBUG - + sed --in-place s@__PATH__@/@g /etc/php/7.4/fpm/pool.d/pixelfed.conf
2022-01-14 21:41:11,897: DEBUG - + test -n pixelfed
2022-01-14 21:41:11,897: DEBUG - + ynh_replace_string --match_string=__NAME__ --replace_string=pixelfed --target_file=/etc/php/7.4/fpm/pool.d/pixelfed.conf
2022-01-14 21:41:11,960: DEBUG - + sed --in-place s@__NAME__@pixelfed@g /etc/php/7.4/fpm/pool.d/pixelfed.conf
2022-01-14 21:41:11,961: DEBUG - + ynh_replace_string --match_string=__NAMETOCHANGE__ --replace_string=pixelfed --target_file=/etc/php/7.4/fpm/pool.d/pixelfed.conf
2022-01-14 21:41:12,024: DEBUG - + sed --in-place s@__NAMETOCHANGE__@pixelfed@g /etc/php/7.4/fpm/pool.d/pixelfed.conf
2022-01-14 21:41:12,026: DEBUG - + ynh_replace_string --match_string=__USER__ --replace_string=pixelfed --target_file=/etc/php/7.4/fpm/pool.d/pixelfed.conf
2022-01-14 21:41:12,089: DEBUG - + sed --in-place s@__USER__@pixelfed@g /etc/php/7.4/fpm/pool.d/pixelfed.conf
2022-01-14 21:41:12,091: DEBUG - + test -n /var/www/pixelfed
2022-01-14 21:41:12,091: DEBUG - + ynh_replace_string --match_string=__FINALPATH__ --replace_string=/var/www/pixelfed --target_file=/etc/php/7.4/fpm/pool.d/pixelfed.conf
2022-01-14 21:41:12,154: DEBUG - + sed --in-place s@__FINALPATH__@/var/www/pixelfed@g /etc/php/7.4/fpm/pool.d/pixelfed.conf
2022-01-14 21:41:12,157: DEBUG - + test -n 7.4
2022-01-14 21:41:12,157: DEBUG - + ynh_replace_string --match_string=__PHPVERSION__ --replace_string=7.4 --target_file=/etc/php/7.4/fpm/pool.d/pixelfed.conf
2022-01-14 21:41:12,221: DEBUG - + sed --in-place s@__PHPVERSION__@7.4@g /etc/php/7.4/fpm/pool.d/pixelfed.conf
2022-01-14 21:41:12,223: DEBUG - + test -n ''
2022-01-14 21:41:12,223: DEBUG - + uniques_vars=($(grep -oP '__[A-Z0-9]+?[A-Z0-9_]*?[A-Z0-9]*?__' $file | sort --unique | sed "s@__\([^.]*\)__@\L\1@g"))
2022-01-14 21:41:12,224: DEBUG - ++ sed 's@__\([^.]*\)__@\L\1@g'
2022-01-14 21:41:12,225: DEBUG - ++ sort --unique
2022-01-14 21:41:12,228: DEBUG - ++ grep -oP '__[A-Z0-9]+?[A-Z0-9_]*?[A-Z0-9]*?__' /etc/php/7.4/fpm/pool.d/pixelfed.conf
2022-01-14 21:41:12,230: DEBUG - + local delimit=@
2022-01-14 21:41:12,230: DEBUG - + for one_var in "${uniques_vars[@]}"
2022-01-14 21:41:12,230: DEBUG - + [[ -v app ]]
2022-01-14 21:41:12,230: DEBUG - + match_string=__APP__
2022-01-14 21:41:12,231: DEBUG - + match_string=__APP__
2022-01-14 21:41:12,231: DEBUG - + replace_string=pixelfed
2022-01-14 21:41:12,231: DEBUG - + replace_string=pixelfed
2022-01-14 21:41:12,231: DEBUG - + replace_string=pixelfed
2022-01-14 21:41:12,231: DEBUG - + sed --in-place s@__APP__@pixelfed@g /etc/php/7.4/fpm/pool.d/pixelfed.conf
2022-01-14 21:41:12,233: DEBUG - + for one_var in "${uniques_vars[@]}"
2022-01-14 21:41:12,233: DEBUG - + [[ -v php_max_children ]]
2022-01-14 21:41:12,233: DEBUG - + match_string=__PHP_MAX_CHILDREN__
2022-01-14 21:41:12,233: DEBUG - + match_string=__PHP_MAX_CHILDREN__
2022-01-14 21:41:12,233: DEBUG - + replace_string=4
2022-01-14 21:41:12,233: DEBUG - + replace_string=4
2022-01-14 21:41:12,233: DEBUG - + replace_string=4
2022-01-14 21:41:12,233: DEBUG - + sed --in-place s@__PHP_MAX_CHILDREN__@4@g /etc/php/7.4/fpm/pool.d/pixelfed.conf
2022-01-14 21:41:12,235: DEBUG - + for one_var in "${uniques_vars[@]}"
2022-01-14 21:41:12,235: DEBUG - + [[ -v php_pm ]]
2022-01-14 21:41:12,235: DEBUG - + match_string=__PHP_PM__
2022-01-14 21:41:12,235: DEBUG - + match_string=__PHP_PM__
2022-01-14 21:41:12,235: DEBUG - + replace_string=ondemand
2022-01-14 21:41:12,236: DEBUG - + replace_string=ondemand
2022-01-14 21:41:12,236: DEBUG - + replace_string=ondemand
2022-01-14 21:41:12,236: DEBUG - + sed --in-place s@__PHP_PM__@ondemand@g /etc/php/7.4/fpm/pool.d/pixelfed.conf
2022-01-14 21:41:12,238: DEBUG - + ynh_store_file_checksum --file=/etc/php/7.4/fpm/pool.d/pixelfed.conf
2022-01-14 21:41:12,238: DEBUG - + update_only=0
2022-01-14 21:41:12,256: DEBUG - + local checksum_setting_name=checksum__etc_php_7.4_fpm_pool.d_pixelfed.conf
2022-01-14 21:41:12,257: DEBUG - ++ cut '--delimiter= ' --fields=1
2022-01-14 21:41:12,259: DEBUG - ++ md5sum /etc/php/7.4/fpm/pool.d/pixelfed.conf
2022-01-14 21:41:12,261: DEBUG - + ynh_app_setting_set --app=pixelfed --key=checksum__etc_php_7.4_fpm_pool.d_pixelfed.conf --value=63310e9e798508ba2bec48d0de8c616c
2022-01-14 21:41:12,261: DEBUG - + local _globalapp=pixelfed
2022-01-14 21:41:12,323: DEBUG - + app=pixelfed
2022-01-14 21:41:12,324: DEBUG - + [[ checksum__etc_php_7.4_fpm_pool.d_pixelfed.conf =~ (unprotected|protected|skipped)_ ]]
2022-01-14 21:41:12,324: DEBUG - + ynh_app_setting set pixelfed checksum__etc_php_7.4_fpm_pool.d_pixelfed.conf 63310e9e798508ba2bec48d0de8c616c
2022-01-14 21:41:12,375: DEBUG - + '[' -n '' ']'
2022-01-14 21:41:12,376: DEBUG - + unset backup_file_checksum
2022-01-14 21:41:12,376: DEBUG - + '[' -e /var/cache/yunohost/app_tmp_work_dirs/app_uzn7fp17/conf/php-fpm.ini ']'
2022-01-14 21:41:12,376: DEBUG - + php-fpm7.4 --test
2022-01-14 21:41:12,377: DEBUG - + php-fpm7.4 --test
2022-01-14 21:41:12,379: WARNING - /usr/share/yunohost/helpers.d/php: line 237: php-fpm7.4: command not found
2022-01-14 21:41:12,380: DEBUG - + true
2022-01-14 21:41:12,380: DEBUG - + ynh_secure_remove --file=/etc/php/7.4/fpm/pool.d/pixelfed.conf
2022-01-14 21:41:12,402: DEBUG - + ynh_die '--message=The new configuration broke php-fpm?'
```

**Comment by yalh76** [comment]
!testme

**Comment by lapineige** [comment]
Guess what ? It worked !

**Pull request merged**
