### PR TITLE
Testing : fix .env default config

### PR DESCRIPTION
**Pull request by lapineige**
https://github.com/YunoHost-Apps/pixelfed_ynh/pull/219#issuecomment-1568049256
Partly revert/partly integrate it.

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by lapineige** [comment]
!testme

**Comment by ericgaspar** [comment]
Shall we merge?

**Comment by lapineige** [comment]
I would have liked to merge only the fix before v2, because it would fix broken installs.
I need to manually test upgrade to v2 first.

**Comment by lapineige** [comment]
Nothing to report after manual testing. Merging. Thanks for your work :)

**Pull request merged**
