### PR TITLE
Upgrade to v0.11.0

### PR DESCRIPTION
**Pull request by lapineige**
## Problem

- New version is available. Changelog : https://github.com/pixelfed/pixelfed/releases/tag/v0.11.0

## Solution

- Upgrade the app

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by lapineige** [comment]
Do we need to change something in `check_process` file ? I don't know how this works.

**Comment by lapineige** [comment]
!testme

**Review by yalh76 — APPROVED** [review]

**Comment by yalh76** [comment]
Thanks a lot, I let you merge and then do the PR from testing to master ;)

**Comment by lapineige** [comment]
I can't try it, my server has some trouble that prevent me from upgrading :sweat_smile:

**Comment by lapineige** [comment]
I would need someone to test the upgrade before merging it… just in case. I can't do it myself for the moment.

**Comment by yalh76** [comment]
> 
> 
> I can't try it, my server has some troubles that prevent me from upgrading 😅
> 
> Do you know if I need to add latest version (which commit ?) to the `check_process` file ?

It's not needed but could help to make it better if you can add it

**Comment by lapineige** [comment]
What commit should I include ? The latest before this PR ?

**Comment by yalh76** [comment]
> 
> 
> What commit should I include ? The latest before this PR ?

Current master : 
0.10.10~ynh4
8ef41895fbd38008f3718e164d0bf3f0d97a2c03

**Comment by yalh76** [comment]
!testme

**Pull request merged**
