### PR TITLE
Add media:fix-nonlocal-driver command

### PR DESCRIPTION
**Pull request by jcrabapple**
## Problem

Profile pictures uploaded to S3 are not displayed

## Solution

Add media:fix-nonlocal-driver command. Fixes s3 media created with invalid FILESYSTEM_DRIVER=s3 configuration

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by jcrabapple** [comment]
!testme

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
Thank you for spotting this. I guess few people used S3 before with Pixelfed&Yunohost 😄

What does this `media:fix-nonlocal-driver` command do ? I can't find it in the manual, apart from https://docs.pixelfed.org/technical-documentation/artisan/#mediafix

I don't understand why there is so many commits and changes... I can't review all of that.
Where is the specific fix ?

**Comment by jcrabapple** [comment]
Sorry I am new to Pull Requests. I forked this repo, merged changes from upstream, and created this PR from my updated fork.

Changes are here:

https://github.com/pixelfed/pixelfed/commit/21714eec342d079c169210c49099b2988bbb205b

**Comment by lapineige** [comment]
So as far as I understand from the upstream fix, this is a command that should be run only if you were using S3 storage with Yunohost default config.
It requires this specific commit from today.

So as far as I understand, this is not something that should be run automatically, but something to run in case of S3 usage and bad configuration (due do Yunohost defaults ?).
And it will require us to upgrade the package first.

Hence I'm closing this PR (feel free to reopen if I understood the issue wrongly), and we will need to make one to upgrade to an upstream new version when it's released, and advertise for that command.
Are you using S3 ? Are all/some medias broken for you ? All uploaded since the release, or all previous too ? *(Any other user affected, please reach out :)*
We may make a specific PR for this use case if no upstream version is released 🤔. I would prefer to stick with released version for the main Yunohost package if that's possible.

**Comment by lapineige** [comment]
> Sorry I am new to Pull Requests. I forked this repo, merged changes from upstream, and created this PR from my updated fork.

The good news is, according to CI, that it's working 😄

**Comment by lapineige** [comment]
According to [that commit](https://github.com/pixelfed/pixelfed/pull/4278/commits/573c88d7b505d0e482a71bd902654c8bf080f97c) description, we may need to patch our default .env file.

**Comment by lapineige** [comment]
Thanks for explaining all that.

> I tried to use Yunohost upgrade commands to upgrade Pixelfed from my forked repo with the updated code, but I am not getting all of the new files like app/Console/Commands/FixMediaDriver.php for some reason.

That is very strange... I wonder how it's linked to the bunch of imported commits. Because you important all Pixelfed codebase, and that's not how Yunohost handle things (you may broke your instance by the way).
What you need is to change Yunohost Pixelfed files archive link. You may use the archive from that commit https://github.com/pixelfed/pixelfed/archive/21714eec342d079c169210c49099b2988bbb205b.tar.gz.
You put that link in `/conf/app.src` file, and adjust the sha256sum accordingly.
It should work, if no other bug is triggered and no breaking change was made.

**Pull request closed without merging**
