### PR TITLE
3-Install/restore fix and package upgrade

### PR DESCRIPTION
**Pull request by yalh76**
## Problem
- *Even if installation was OK, app can"t be used*

## Solution
- *Upgrade to last version 0.8.4 commit*
- *switch from ynh_install_php7 to Yunohost experimental helper ynh_install_php*
- *switch from ynh_add_php71-fpm_config to Yunohost helper ynh_add_fpm_config*
- *switch to PHP 7.2*
- *switch to Yunohost experimental helper ynh_install_composer*
- *fix Install (in particular, for now pixelfeed seems to not be able to work in a sub_dir*

## PR Status
- [x] Code finished.
- [ ] Tested with Package_check.
- [x] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Validation
---
- [ ] **Code review**
- [ ] **Approval (LGTM)**  

- **CI succeeded** :

### CODE REVIEW

**Comment by yalh76** [comment]
For now stuck by a bug with ynh_add_secure_repos__2: https://github.com/YunoHost-Apps/Experimental_helpers/issues/36

**Comment by Jibec** [comment]
I fixed conflict and merged it in a testing branch. Please use this from now on.

**Comment by yalh76** [comment]
@Jibec. as you merged the PR, I can't see where yours reviews apply, I will move on the testing branch

**Comment by yalh76** [comment]
> 
> 
> can youplease use official releases? https://github.com/pixelfed/pixelfed/releases/tag/v0.8.0
> 
> I'm uncomfortable about using commits instead of real releases, because using commits makes the responsibility on us, while it should be on the project (to tell which commit is the one to use for production)

I completely agree with you and usually I also prefer to use a tagged version. But when checking [what version pixelfed servers are using](https://the-federation.info/pixelfed): only 25% of sites use 0.8.0rc1 and more than 60% use an upper version (mainly 0.8.1 and 0.8.4 (36%) )

**Pull request closed without merging**
