### PR TITLE
Testing : v0.11.2 + php 7.4

### PR DESCRIPTION
**Pull request by lapineige**
## Problem

- A new Pixelfed version is available : v0.11.2 https://github.com/pixelfed/pixelfed/releases/tag/v0.11.2
- Php 7.3 is no longer supported https://github.com/pixelfed/pixelfed/pull/3041

## Solution

- Upgrade Pixelfed
- Switch to php 7.4

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by lapineige** [comment]
Do we need to run the CI again ? (it's the very same version)

Should we only wait a few days to make sure people had some time to test it ?

**Comment by yalh76** [comment]
I love running the CI ^^

!testme

**Comment by lapineige** [comment]
Well I didn't want to put some extra load on the CI while it was the exact same version :sweat_smile:
(I launched a call for testing btw)

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by jhammons** [comment]
I just wanted to add that this works perfectly for my on my production instance. Thank you!

**Comment by lapineige** [comment]
I received 5 positive feedbacks on this PR, either for fresh installs or upgrades. And only one negative one, that was not related to this upgrade.
It also fixes #160.

Then I consider it's ready to be merged.

Thanks @yalh76 for you work and to all testers :)

**Pull request merged**
