### PR TITLE
Switch to PHP8

### PR DESCRIPTION
**Pull request by yalh76**
## Solution

- *Switch to PHP8*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by yalh76** [comment]
!testme

**Comment by lapineige** [comment]
Ah, well… I was trying it manually, and I was going to say I had an error and we should wait 😅


```
php8.0 /var/www/pixelfed/composer.phar update -d /var/www/pixelfed --no-interaction --no-ansi
Deprecation Notice: Required parameter $path follows optional parameter $schema in phar:///var/www/pixelfed/composer.phar/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/UndefinedConstraint.php:62
Deprecation Notice: Required parameter $path follows optional parameter $schema in phar:///var/www/pixelfed/composer.phar/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/UndefinedConstraint.php:108
Deprecation Notice: Method ReflectionParameter::getClass() is deprecated in phar:///var/www/pixelfed/composer.phar/src/Composer/Repository/RepositoryManager.php:130
 Deprecation Notice: Method ReflectionParameter::getClass() is deprecated in phar:///var/www/pixelfed/composer.phar/src/Composer/Repository/RepositoryManager.php:130
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Warning from https://repo.packagist.org: Support for Composer 1 is deprecated and some packages will not be available. You should upgrade to Composer 2. See https://blog.packagist.com/deprecating-composer-1-support/
Info from https://repo.packagist.org: [37;44m#StandWith[30;43mUkraine[0m
Updating dependencies (including require-dev)
PHP Fatal error: Uncaught ArgumentCountError: array_merge() does not accept unknown named parameters in phar:///var/www/pixelfed/composer.phar/src/Composer/DependencyResolver/DefaultPolicy.php:84
Stack trace:
 #0 [internal function]: array_merge()
#1 phar:///var/www/pixelfed/composer.phar/src/Composer/DependencyResolver/DefaultPolicy.php(84): call_user_func_array()
 #2 phar:///var/www/pixelfed/composer.phar/src/Composer/DependencyResolver/Solver.php(387): Composer\DependencyResolver\DefaultPolicy->selectPreferredPackages()
 - #3 phar:///var/www/pixelfed/composer.phar/src/Composer/DependencyResolver/Solver.php(742): Composer\DependencyResolver\Solver->selectAndInstall()
#4 phar:///var/www/pixelfed/composer.phar/src/Composer/DependencyResolver/Solver.php(231): Composer\DependencyResolver\Solver->runSat()
#5 phar:///var/www/pixelfed/composer.phar/src/Composer/Installer.php(475): Composer\DependencyResolver\Solver->solve()
#6 phar:///var/www/pixelfed/composer.phar/src/Composer/Installer.php(229): Composer\Installer->doInstall()
#7 phar:///var/www/pixelfed/composer.phar/src/Composer/Command/UpdateCommand.php(163): Composer\Installer->run()
#8 phar:///var/www/pixelfed/composer.phar/vendor/symfony/console/Command/Command.php(245): Composer\Command\UpdateCommand->execute()
#9 phar:///var/www/pixelfed/composer.phar/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run()
#10 phar:///var/www/pixelfed/composer.phar/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand()
#11 phar:///var/www/pixelfed/composer.phar/src/Composer/Console/Application.php(258): Symfony\Component\Console\Application->doRun()
#12 phar:///var/www/pixelfed/composer.phar/vendor/symfony/console/Application.php(117): Composer\Console\Application->doRun()
#13 phar:///var/www/pixelfed/composer.phar/src/Composer/Console/Application.php(104): Symfony\Component\Console\Application->run()
#14 phar:///var/www/pixelfed/composer.phar/bin/composer(61): Composer\Console\Application->run()
#15 /var/www/pixelfed/composer.phar(24): require('...')
#16 {main}
thrown in phar:///var/www/pixelfed/composer.phar/src/Composer/DependencyResolver/DefaultPolicy.php on line 84
```

**Comment by lapineige** [comment]
Also… how do we handle this composer v2 migration ?

**Comment by lapineige** [comment]
Oh… that might be a Composer v1 issue… https://github.com/composer/composer/issues/9097#issuecomment-737608580

**Comment by lapineige** [comment]
Uh wait, why my log says at its beginning `YNH_COMPOSER_VERSION=2.1.5` ?!
Oh ok, it's here : https://github.com/YunoHost-Apps/pixelfed_ynh/blob/master/scripts/_common.sh#L9

So why is this composer v1 ?
>
`Warning from https://repo.packagist.org: Support for Composer 1 is deprecated and some packages will not be available. You should upgrade to Composer 2. See https://blog.packagist.com/deprecating-composer-1-support/`

And why don't we use `--composerversion` option (from https://yunohost.org/en/packaging_apps_helpers#ynh-install-composer) ? 🤔

I'll make a PR.

**Pull request merged**
